const fetch = require('node-fetch');

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }
    
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }
    
    try {
        const { image } = req.body;
        
        if (!image) {
            return res.status(400).json({ error: 'No image provided' });
        }
        
        const hfToken = process.env.HF_TOKEN;
        
        if (!hfToken) {
            return res.status(500).json({ error: 'HF_TOKEN not configured' });
        }
        
        // Обробляємо зображення
        let imageBase64 = image;
        if (image.includes('base64,')) {
            imageBase64 = image.split('base64,')[1];
        }
        
        const imageBuffer = Buffer.from(imageBase64, 'base64');
        
        // Використовуємо кращу модель для розпізнавання їжі
        const response = await fetch(
            'https://router.huggingface.co/hf-inference/models/CreatorJarvis/FoodExtract-Vision-SmolVLM2-500M-fine-tune',
            {
                method: 'POST',
                headers: {
                    'Authorization': 'Bearer ' + hfToken,
                    'Content-Type': 'application/octet-stream'
                },
                body: imageBuffer,
                timeout: 60000
            }
        );
        
        const data = await response.json();
        
        // База калорій для українських страв
        const calorieDB = {
            // М'ясо та ковбаси
            'sausage': { name: 'Сосиска', cal: 150 },
            'hot dog': { name: 'Хот-дог', cal: 290 },
            'hotdog': { name: 'Хот-дог', cal: 290 },
            'bacon': { name: 'Бекон', cal: 540 },
            'ham': { name: 'Шинка', cal: 145 },
            'salami': { name: 'Саламі', cal: 330 },
            'pepperoni': { name: 'Пепероні', cal: 350 },
            'prosciutto': { name: 'Прошутто', cal: 250 },
            'chorizo': { name: 'Чорізо', cal: 455 },
            
            // Овочі
            'tomato': { name: 'Помідор', cal: 18 },
            'tomatoes': { name: 'Помідори', cal: 18 },
            'cucumber': { name: 'Огірок', cal: 15 },
            'carrot': { name: 'Морква', cal: 41 },
            'carrots': { name: 'Морква', cal: 41 },
            'onion': { name: 'Цибуля', cal: 40 },
            'potato': { name: 'Картопля', cal: 95 },
            'potatoes': { name: 'Картопля', cal: 95 },
            'pepper': { name: 'Перець', cal: 27 },
            'lettuce': { name: 'Салат', cal: 15 },
            'salad': { name: 'Салат', cal: 20 },
            'cabbage': { name: 'Капуста', cal: 25 },
            'broccoli': { name: 'Броколі', cal: 34 },
            'cauliflower': { name: 'Цвітна капуста', cal: 25 },
            'spinach': { name: 'Шпинат', cal: 23 },
            'mushroom': { name: 'Гриби', cal: 22 },
            'mushrooms': { name: 'Гриби', cal: 22 },
            'garlic': { name: 'Часник', cal: 149 },
            'corn': { name: 'Кукурудза', cal: 86 },
            'avocado': { name: 'Авокадо', cal: 160 },
            'beet': { name: 'Буряк', cal: 43 },
            'beets': { name: 'Буряк', cal: 43 },
            'eggplant': { name: 'Баклажан', cal: 25 },
            'zucchini': { name: 'Кабачок', cal: 17 },
            'pumpkin': { name: 'Гарбуз', cal: 26 },
            'radish': { name: 'Редиска', cal: 16 },
            'celery': { name: 'Селера', cal: 14 },
            'asparagus': { name: 'Спаржа', cal: 20 },
            'peas': { name: 'Горох', cal: 81 },
            'green beans': { name: 'Квасоля', cal: 31 },
            
            // Фрукти
            'apple': { name: 'Яблуко', cal: 52 },
            'apples': { name: 'Яблука', cal: 52 },
            'banana': { name: 'Банан', cal: 95 },
            'bananas': { name: 'Бани', cal: 95 },
            'orange': { name: 'Апельсин', cal: 43 },
            'oranges': { name: 'Апельсини', cal: 43 },
            'grape': { name: 'Виноград', cal: 69 },
            'grapes': { name: 'Виноград', cal: 69 },
            'strawberry': { name: 'Полуниця', cal: 33 },
            'strawberries': { name: 'Полуниця', cal: 33 },
            'blueberry': { name: 'Чорниця', cal: 57 },
            'blueberries': { name: 'Чорниця', cal: 57 },
            'raspberry': { name: 'Малина', cal: 52 },
            'cherry': { name: 'Вишня', cal: 50 },
            'cherries': { name: 'Вишня', cal: 50 },
            'peach': { name: 'Персик', cal: 40 },
            'pear': { name: 'Груша', cal: 57 },
            'mango': { name: 'Манго', cal: 60 },
            'pineapple': { name: 'Ананас', cal: 50 },
            'watermelon': { name: 'Кавун', cal: 30 },
            'melon': { name: 'Диня', cal: 34 },
            'kiwi': { name: 'Ківі', cal: 61 },
            'lemon': { name: 'Лимон', cal: 29 },
            'lime': { name: 'Лайм', cal: 30 },
            'pomegranate': { name: 'Гранат', cal: 83 },
            'fig': { name: 'Інжир', cal: 74 },
            'dates': { name: 'Фініки', cal: 277 },
            'coconut': { name: 'Кокос', cal: 354 },
            'olive': { name: 'Оливка', cal: 115 },
            'olives': { name: 'Оливки', cal: 115 },
            
            // Молочні продукти
            'cheese': { name: 'Сир', cal: 350 },
            'cheddar': { name: 'Чеддер', cal: 403 },
            'mozzarella': { name: 'Моцарелла', cal: 280 },
            'parmesan': { name: 'Пармезан', cal: 431 },
            'brie': { name: 'Брі', cal: 334 },
            'feta': { name: 'Фета', cal: 264 },
            'cottage cheese': { name: 'Сир творожний', cal: 98 },
            'yogurt': { name: 'Йогурт', cal: 60 },
            'milk': { name: 'Молоко', cal: 42 },
            'cream': { name: 'Вершки', cal: 195 },
            'butter': { name: 'Масло', cal: 717 },
            'sour cream': { name: 'Сметана', cal: 198 },
            'ice cream': { name: 'Морозиво', cal: 207 },
            
            // Хліб та випічка
            'bread': { name: 'Хліб', cal: 265 },
            'toast': { name: 'Тост', cal: 260 },
            'baguette': { name: 'Багет', cal: 270 },
            'croissant': { name: 'Круассан', cal: 406 },
            'roll': { name: 'Булка', cal: 320 },
            'bun': { name: 'Булочка', cal: 310 },
            'muffin': { name: 'Маффін', cal: 340 },
            'pancake': { name: 'Млинець', cal: 227 },
            'pancakes': { name: 'Млинці', cal: 227 },
            'waffle': { name: 'Вафля', cal: 291 },
            'waffles': { name: 'Вафлі', cal: 291 },
            'donut': { name: 'Пончик', cal: 452 },
            'donuts': { name: 'Пончики', cal: 452 },
            'bagel': { name: 'Бейгл', cal: 250 },
            'tortilla': { name: 'Тортилья', cal: 237 },
            'pita': { name: 'Піта', cal: 275 },
            'naan': { name: 'Наан', cal: 310 },
            'crackers': { name: 'Сухарики', cal: 502 },
            'cookies': { name: 'Печиво', cal: 488 },
            'cookie': { name: 'Печиво', cal: 488 },
            
            // М'ясо
            'chicken': { name: 'Курка', cal: 239 },
            'chicken breast': { name: 'Куряча грудка', cal: 165 },
            'chicken wing': { name: 'Куряче крило', cal: 203 },
            'chicken thigh': { name: 'Куряче стегно', cal: 209 },
            'turkey': { name: 'Індичка', cal: 135 },
            'beef': { name: 'Яловичина', cal: 250 },
            'steak': { name: 'Стейк', cal: 271 },
            'pork': { name: 'Свинина', cal: 242 },
            'lamb': { name: 'Баранина', cal: 294 },
            'duck': { name: 'Качка', cal: 337 },
            'veal': { name: 'Телятина', cal: 175 },
            'meatball': { name: 'Котлета', cal: 250 },
            'meatballs': { name: 'Котлети', cal: 250 },
            'hamburger': { name: 'Бургер', cal: 295 },
            'burger': { name: 'Бургер', cal: 295 },
            'cheeseburger': { name: 'Чізбургер', cal: 354 },
            'pulled pork': { name: 'Тягнуте м\'ясо', cal: 260 },
            'ribs': { name: 'Реберця', cal: 285 },
            'bacon': { name: 'Бекон', cal: 541 },
            'sausage': { name: 'Сосиска', cal: 301 },
            'salami': { name: 'Саламі', cal: 336 },
            'pepperoni': { name: 'Пепероні', cal: 504 },
            
            // Риба та морепродукти
            'salmon': { name: 'Лосось', cal: 208 },
            'tuna': { name: 'Тунець', cal: 132 },
            'cod': { name: 'Треска', cal: 82 },
            'shrimp': { name: 'Креветки', cal: 99 },
            'prawn': { name: 'Креветки', cal: 99 },
            'crab': { name: 'Краб', cal: 97 },
            'lobster': { name: 'Лангуст', cal: 89 },
            'mussel': { name: 'Мідії', cal: 86 },
            'oyster': { name: 'Устриці', cal: 81 },
            'squid': { name: 'Кальмар', cal: 75 },
            'octopus': { name: 'Восьминіг', cal: 82 },
            'sardine': { name: 'Сардина', cal: 208 },
            'anchovy': { name: 'Анчус', cal: 131 },
            'fish': { name: 'Риба', cal: 206 },
            
            // Готові страви
            'pizza': { name: 'Піца', cal: 266 },
            'pasta': { name: 'Паста', cal: 131 },
            'spaghetti': { name: 'Спагетті', cal: 158 },
            'lasagna': { name: 'Лазанья', cal: 135 },
            'macaroni': { name: 'Макарони', cal: 131 },
            'noodles': { name: 'Локшина', cal: 138 },
            'ramen': { name: 'Рамен', cal: 191 },
            'sushi': { name: 'Суші', cal: 143 },
            'sashimi': { name: 'Сашимі', cal: 143 },
            'tempura': { name: 'Темпура', cal: 227 },
            'fried rice': { name: 'Смажений рис', cal: 163 },
            'risotto': { name: 'Різотто', cal: 120 },
            'paella': { name: 'Паелья', cal: 172 },
            'curry': { name: 'Каррі', cal: 125 },
            'stir fry': { name: 'Смажені овочі', cal: 110 },
            'soup': { name: 'Суп', cal: 50 },
            'stew': { name: 'Тушковане', cal: 80 },
            'chili': { name: 'Чилі', cal: 110 },
            'tacos': { name: 'Тако', cal: 210 },
            'burrito': { name: 'Бурріто', cal: 206 },
            'quesadilla': { name: 'Кесаділья', cal: 227 },
            'nachos': { name: 'Начос', cal: 316 },
            'falafel': { name: 'Фалафель', cal: 333 },
            'hummus': { name: 'Хумус', cal: 166 },
            'kebab': { name: 'Кебаб', cal: 279 },
            'shawarma': { name: 'Шаварма', cal: 230 },
            'gyros': { name: 'Гірос', cal: 215 },
            'sandwich': { name: 'Сендвіч', cal: 252 },
            'wrap': { name: 'Рол', cal: 230 },
            'burger': { name: 'Бургер', cal: 295 },
            'hot dog': { name: 'Хот-дог', cal: 290 },
            'french fries': { name: 'Картопля фрі', cal: 312 },
            'fries': { name: 'Картопля фрі', cal: 312 },
            'chips': { name: 'Чіпси', cal: 536 },
            'nachos': { name: 'Начос', cal: 316 },
            'onion rings': { name: 'Кільця цибулі', cal: 411 },
            'mozzarella sticks': { name: 'Палички моцарели', cal: 360 },
            'spring rolls': { name: 'Літні роли', cal: 149 },
            'dumplings': { name: 'Вареники', cal: 210 },
            'pierogi': { name: 'Пельмені', cal: 200 },
            'ravioli': { name: 'Равіолі', cal: 180 },
            'gnocchi': { name: 'Ньоккі', cal: 133 },
            'tortellini': { name: 'Тортелліні', cal: 160 },
            
            // Салати
            'caesar salad': { name: 'Салат Цезар', cal: 127 },
            'greek salad': { name: 'Грецький салат', cal: 100 },
            'cobb salad': { name: 'Кобб-салат', cal: 140 },
            'caprese': { name: 'Капрезе', cal: 160 },
            'coleslaw': { name: 'Коуслав', cal: 150 },
            'potato salad': { name: 'Картопляний салат', cal: 143 },
            'pasta salad': { name: 'Паста-салат', cal: 130 },
            'fruit salad': { name: 'Фруктовий салат', cal: 50 },
            'garden salad': { name: 'Овочевий салат', cal: 20 },
            'spinach salad': { name: 'Салат зі шпинатом', cal: 70 },
            
            // Солодощі
            'chocolate': { name: 'Шоколад', cal: 546 },
            'cake': { name: 'Торт', cal: 352 },
            'pie': { name: 'Пиріг', cal: 237 },
            'brownie': { name: 'Брауні', cal: 466 },
            'cookie': { name: 'Печиво', cal: 488 },
            'candy': { name: 'Цукерки', cal: 394 },
            'gummy': { name: 'Желейні цукерки', cal: 350 },
            'lollipop': { name: 'Льодяник', cal: 380 },
            'ice cream': { name: 'Морозиво', cal: 207 },
            'gelato': { name: 'Джелато', cal: 191 },
            'pudding': { name: 'Пудинг', cal: 122 },
            'jello': { name: 'Желе', cal: 63 },
            'cheesecake': { name: 'Чізкейк', cal: 321 },
            'tiramisu': { name: 'Тірамісу', cal: 250 },
            'cinnamon roll': { name: 'Булочка з корицею', cal: 320 },
            'croissant': { name: 'Круассан', cal: 406 },
            'muffin': { name: 'Маффін', cal: 340 },
            'cupcake': { name: 'Кекс', cal: 305 },
            'macaron': { name: 'Макарон', cal: 350 },
            'eclair': { name: 'Еклер', cal: 320 },
            'cream puff': { name: 'Профітроль', cal: 300 },
            'donut': { name: 'Пончик', cal: 452 },
            'churro': { name: 'Чуррос', cal: 350 },
            'baklava': { name: 'Баклава', cal: 527 },
            'cannoli': { name: 'Каннолі', cal: 310 },
            'tiramisu': { name: 'Тірамісу', cal: 250 },
            'creme brulee': { name: 'Крем-брюле', cal: 350 },
            'panna cotta': { name: 'Панна-котта', cal: 310 },
            'mousse': { name: 'Мус', cal: 180 },
            'sorbet': { name: 'Сорбе', cal: 120 },
            'sherbet': { name: 'Шербет', cal: 130 },
            
            // Напої
            'coffee': { name: 'Кава', cal: 2 },
            'tea': { name: 'Чай', cal: 2 },
            'juice': { name: 'Сік', cal: 45 },
            'soda': { name: 'Газировка', cal: 41 },
            'beer': { name: 'Пиво', cal: 43 },
            'wine': { name: 'Вино', cal: 83 },
            'cocktail': { name: 'Коктейль', cal: 150 },
            'milkshake': { name: 'Мілкшейк', cal: 230 },
            'smoothie': { name: 'Смузі', cal: 120 },
            'water': { name: 'Вода', cal: 0 },
            'lemonade': { name: 'Лимонад', cal: 40 },
            'hot chocolate': { name: 'Какао', cal: 75 },
            'latte': { name: 'Латте', cal: 135 },
            'cappuccino': { name: 'Капучіно', cal: 80 },
            'espresso': { name: 'Еспресо', cal: 5 },
            'mocha': { name: 'Мокко', cal: 166 },
            'frappuccino': { name: 'Фрапучіно', cal: 230 },
            'milk': { name: 'Молоко', cal: 42 },
            'chocolate milk': { name: 'Шоколадне молоко', cal: 83 },
            'buttermilk': { name: 'Кисле молоко', cal: 40 },
            'kefir': { name: 'Кефір', cal: 40 },
            'kumis': { name: 'Кумис', cal: 40 },
            'ayran': { name: 'Айран', cal: 25 },
            'lassi': { name: 'Лассі', cal: 70 },
            
            // Горіхи та насіння
            'nuts': { name: 'Горіхи', cal: 607 },
            'almonds': { name: 'Мигдаль', cal: 579 },
            'cashews': { name: 'Кеш\'ю', cal: 553 },
            'peanuts': { name: 'Арахіс', cal: 567 },
            'walnuts': { name: 'Волоські горіхи', cal: 654 },
            'pecans': { name: 'Пекан', cal: 691 },
            'pistachios': { name: 'Фісташки', cal: 560 },
            'hazelnuts': { name: 'Фундук', cal: 628 },
            'macadamia': { name: 'Макадамія', cal: 718 },
            'brazil nuts': { name: 'Бразильські горіхи', cal: 659 },
            'pine nuts': { name: 'Кедрові горішки', cal: 673 },
            'sunflower seeds': { name: 'Насіння соняшника', cal: 584 },
            'pumpkin seeds': { name: 'Гарбузове насіння', cal: 559 },
            'sesame seeds': { name: 'Кунжут', cal: 573 },
            'chia seeds': { name: 'Насіння чіа', cal: 486 },
            'flax seeds': { name: 'Льон', cal: 534 },
            'hemp seeds': { name: 'Конопляне насіння', cal: 553',
            
            // Бобові
            'beans': { name: 'Квасоля', cal: 127 },
            'lentils': { name: 'Сочевиця', cal: 116 },
            'chickpeas': { name: 'Нут', cal: 164 },
            'hummus': { name: 'Хумус', cal: 166 },
            'tofu': { name: 'Тофу', cal: 76 },
            'tempeh': { name: 'Темпех', cal: 195 },
            'edamame': { name: 'Едамаме', cal: 121 },
            'soy': { name: 'Соя', cal: 173 },
            
            // Соуси
            'ketchup': { name: 'Кетчуп', cal: 112 },
            'mustard': { name: 'Гірчиця', cal: 66 },
            'mayonnaise': { name: 'Майонез', cal: 680 },
            'bbq sauce': { name: 'Соус BBQ', cal: 172 },
            'ranch': { name: 'Ранч', cal: 129 },
            'salad dressing': { name: 'Заправка', cal: 120 },
            'vinaigrette': { name: 'Вінегрет', cal: 104 },
            'salsa': { name: 'Сальса', cal: 36 },
            'guacamole': { name: 'Гуакамоле', cal: 151 },
            'pesto': { name: 'Песто', cal: 388 },
            'marinara': { name: 'Марінара', cal: 68 },
            'alfredo': { name: 'Альфредо', cal: 125 },
            'soy sauce': { name: 'Соєвий соус', cal: 53 },
            'hot sauce': { name: 'Гострий соус', cal: 11 },
            'teriyaki': { name: 'Теріякі', cal: 89 },
            'sriracha': { name: 'Срірача', cal: 93 },
            'tabasco': { name: 'Табаско', cal: 12',
            
            // Сніданок
            'cereal': { name: 'Гранули', cal: 379 },
            'oatmeal': { name: 'Вівсянка', cal: 68 },
            'porridge': { name: 'Каша', cal: 71 },
            'granola': { name: 'Гранола', cal: 471 },
            'muesli': { name: 'Мюслі', cal: 340 },
            'yogurt': { name: 'Йогурт', cal: 60 },
            'omelette': { name: 'Омлет', cal: 154 },
            'scrambled eggs': { name: 'Яйця-болтунці', cal: 148 },
            'fried eggs': { name: 'Смажені яйця', cal: 196 },
            'poached eggs': { name: 'Яйця пашот', cal: 143 },
            'boiled eggs': { name: 'Варені яйця', cal: 155 },
            'french toast': { name: 'Тост з яйцем', cal: 227 },
            'waffles': { name: 'Вафлі', cal: 291 },
            'pancakes': { name: 'Млинці', cal: 227 },
            'crepes': { name: 'Крепи', cal: 167 },
            'bagel': { name: 'Бейгл', cal: 250 },
            'muffin': { name: 'Маффін', cal: 340 },
            'croissant': { name: 'Круассан', cal: 406 },
            'danish': { name: 'Данська', cal: 380 },
            'scone': { name: 'Скон', cal: 340',
            
            // Піца
            'pepperoni pizza': { name: 'Піца з пепероні', cal: 311 },
            'cheese pizza': { name: 'Сирна піца', cal: 272 },
            'margherita': { name: 'Маргарита', cal: 250 },
            'hawaiian pizza': { name: 'Гавайська піца', cal: 240 },
            'meat lovers': { name: 'Піца з м\'ясом', cal: 320 },
            'veggie pizza': { name: 'Овочева піца', cal: 220 },
            'bbq chicken pizza': { name: 'Піца з BBQ куркою', cal: 280',
            
            // Бургери
            'cheeseburger': { name: 'Чізбургер', cal: 354 },
            'bacon cheeseburger': { name: 'Бекон-чізбургер', cal: 390 },
            'double cheeseburger': { name: 'Двійний чізбургер', cal: 460 },
            'veggie burger': { name: 'Овочевий бургер', cal: 220 },
            'turkey burger': { name: 'Бургер з індички', cal: 240 },
            'chicken burger': { name: 'Курячий бургер', cal: 280 },
            'fish burger': { name: 'Рибний бургер', cal: 260',
            
            // Торти
            'chocolate cake': { name: 'Шоколадний торт', cal: 352 },
            'vanilla cake': { name: 'Ванільний торт', cal: 340 },
            'red velvet': { name: 'Червоний оксамит', cal: 370 },
            'carrot cake': { name: 'Морквяний торт', cal: 340 },
            'cheesecake': { name: 'Чізкейк', cal: 321 },
            'tiramisu': { name: 'Тірамісу', cal: 250 },
            'black forest': { name: 'Чорний ліс', cal: 340 },
            'sponge cake': { name: 'Бісквіт', cal: 320 },
            'fruit cake': { name: 'Фруктовий торт', cal: 320 },
            'pound cake': { name: 'Паунд-кейк', cal: 380',
            
            // Пироги
            'apple pie': { name: 'Яблучний пиріг', cal: 237 },
            'cherry pie': { name: 'Вишневий пиріг', cal: 260 },
            'pumpkin pie': { name: 'Гарбузовий пиріг', cal: 243 },
            'pecan pie': { name: 'Пекановий пиріг', cal: 430 },
            'blueberry pie': { name: 'Чорничний пиріг', cal: 245 },
            'key lime pie': { name: 'Лаймовий пиріг', cal: 360 },
            'lemon meringue': { name: 'Лимонний меренг', cal: 310',
            
            // Морозиво
            'vanilla ice cream': { name: 'Ванільне морозиво', cal: 207 },
            'chocolate ice cream': { name: 'Шоколадне морозиво', cal: 216 },
            'strawberry ice cream': { name: 'Полуничне морозиво', cal: 192 },
            'cookie dough': { name: 'Морозиво з тістом', cal: 230 },
            'mint chocolate chip': { name: 'М\'ятне з шоколадом', cal: 215 },
            'rocky road': { name: 'Рокі-роуд', cal: 240 },
            'neapolitan': { name: 'Неаполітан', cal: 200 },
            'sorbet': { name: 'Сорбе', cal: 120 },
            'gelato': { name: 'Джелато', cal: 191 },
            'frozen yogurt': { name: 'Заморожений йогурт', cal: 127',
            
            // Супи
            'chicken soup': { name: 'Курячий суп', cal: 56 },
            'tomato soup': { name: 'Томатний суп', cal: 72 },
            'minestrone': { name: 'Мінестроне', cal: 82 },
            'clam chowder': { name: 'Молюсковий суп', cal: 101 },
            'mushroom soup': { name: 'Грибний суп', cal: 60 },
            'onion soup': { name: 'Цибулевий суп', cal: 48 },
            'broccoli soup': { name: 'Суп з броколі', cal: 60 },
            'pumpkin soup': { name: 'Гарбузовий суп', cal: 55 },
            'butternut squash': { name: 'Гарбузовий суп', cal: 60 },
            'lentil soup': { name: 'Сочевичний суп', cal: 130 },
            'vegetable soup': { name: 'Овочевий суп', cal: 50 },
            'beef stew': { name: 'Тушкована яловичина', cal: 110',
            
            // Паста
            'spaghetti bolognese': { name: 'Спагетті Болоньєзе', cal: 150 },
            'spaghetti carbonara': { name: 'Спагетті Карбонара', cal: 190 },
            'fettuccine alfredo': { name: 'Феттучіні Альфредо', cal: 220 },
            'penne': { name: 'Пенне', cal: 130 },
            'rigatoni': { name: 'Рігатоні', cal: 130 },
            'linguine': { name: 'Лінгвіне', cal: 130 },
            'farfalle': { name: 'Метелики', cal: 130 },
            'tortellini': { name: 'Тортелліні', cal: 160 },
            'ravioli': { name: 'Равіолі', cal: 180 },
            'lasagna': { name: 'Лазанья', cal: 135',
            
            // Суші
            'california roll': { name: 'Каліфорнія', cal: 143 },
            'salmon roll': { name: 'Рол з лососем', cal: 160 },
            'tuna roll': { name: 'Рол з тунцем', cal: 150 },
            'shrimp tempura': { name: 'Креветка темпура', cal: 170 },
            'dragon roll': { name: 'Драгон', cal: 180 },
            'rainbow roll': { name: 'Рейнбоу', cal: 175 },
            'philadelphia': { name: 'Філадельфія', cal: 165 },
            'spicy tuna': { name: 'Гострий тунець', cal: 155 },
            'maki': { name: 'Макі', cal: 140 },
            'nigiri': { name: 'Нігірі', cal: 145 },
            'sashimi': { name: 'Сашимі', cal: 143',
            
            // Мексиканська
            'taco': { name: 'Тако', cal: 210 },
            'burrito': { name: 'Бурріто', cal: 206 },
            'quesadilla': { name: 'Кесаділья', cal: 227 },
            'enchilada': { name: 'Енчілада', cal: 190 },
            'tostada': { name: 'Тостада', cal: 180 },
            'chimichanga': { name: 'Чимічанга', cal: 240 },
            'empanada': { name: 'Емпанада', cal: 250 },
            'tamale': { name: 'Тамале', cal: 220',
            
            // Азіатська
            'pad thai': { name: 'Пад Тай', cal: 190 },
            'green curry': { name: 'Зелене каррі', cal: 120 },
            'red curry': { name: 'Червоне каррі', cal: 130 },
            'massaman curry': { name: 'Массаман', cal: 140 },
            'tom yum': { name: 'Том Ям', cal: 80 },
            'pho': { name: 'Фо', cal: 120 },
            'bibimbap': { name: 'Бібімбап', cal: 180 },
            'kung pao': { name: 'Кунг-пао', cal: 180 },
            'sweet and sour': { name: 'Кисло-солодке', cal: 150 },
            'general tso': { name: 'Дженерал Цо', cal: 200 },
            'orange chicken': { name: 'Апельсинова курка', cal: 220 },
            'fried rice': { name: 'Смажений рис', cal: 163 },
            'lo mein': { name: 'Ло мейн', cal: 170 },
            'chow mein': { name: 'Чоу мейн', cal: 180 },
            'dumplings': { name: 'Пельмені', cal: 200 },
            'wonton': { name: 'Вонтон', cal: 160 },
            'egg roll': { name: 'Яєчний рол', cal: 200 },
            'spring roll': { name: 'Літній рол', cal: 149 },
            'samosa': { name: 'Самоса', cal: 260 },
            'naan': { name: 'Наан', cal: 310 },
            'biryani': { name: 'Бір\'яні', cal: 180 },
            'tikka masala': { name: 'Тіка Масала', cal: 160 },
            'butter chicken': { name: 'Курка в маслі', cal: 190',
            
            // Середземноморська
            'hummus': { name: 'Хумус', cal: 166 },
            'falafel': { name: 'Фалафель', cal: 333 },
            'shakshuka': { name: 'Шакшука', cal: 140 },
            'kebab': { name: 'Кебаб', cal: 279 },
            'gyro': { name: 'Гірос', cal: 215 },
            'moussaka': { name: 'Мусака', cal: 130 },
            'spanakopita': { name: 'Спанакопіта', cal: 230 },
            'dolma': { name: 'Долма', cal: 120 },
            'baklava': { name: 'Баклава', cal: 527 },
            'tzatziki': { name: 'Цацикі', cal: 100 },
            'tabbouleh': { name: 'Таббуле', cal: 100 },
            'fattoush': { name: 'Фаттуш', cal: 90 },
            'baba ganoush': { name: 'Баба-гануш', cal: 130',
            
            // Українська
            'borscht': { name: 'Борщ', cal: 50 },
            'varenyky': { name: 'Вареники', cal: 210 },
            'deruny': { name: 'Деруни', cal: 180 },
            'holubtsi': { name: 'Голубці', cal: 130 },
            'salo': { name: 'Сало', cal: 800 },
            'kholodets': { name: 'Холодець', cal: 150 },
            'pampushky': { name: 'Пампушки', cal: 310 },
            'uzvar': { name: 'Узвар', cal: 40 },
            'kutia': { name: 'Кутя', cal: 320 },
            'pyrizhky': { name: 'Пиріжки', cal: 280 },
            'banosh': { name: 'Банош', cal: 150 },
            'kulish': { name: 'Куліш', cal: 120 },
            'bandurky': { name: 'Бандурки', cal: 200 },
            'zrazy': { name: 'Зрази', cal: 180 },
            'kovbasa': { name: 'Ковбаса', cal: 260 },
            'kovbasy': { name: 'Ковбаси', cal: 260 },
            'syrnyky': { name: 'Сирники', cal: 180 },
            'mlyntsi': { name: 'Млинці', cal: 230 },
            'kasha': { name: 'Каша', cal: 100 },
            'kompot': { name: 'Компот', cal: 40 },
            'kysil': { name: 'Кисіль', cal: 60',
            
            // Російська
            'pelmeni': { name: 'Пельмені', cal: 200 },
            'blini': { name: 'Бліни', cal: 230 },
            'pirozhki': { name: 'Пиріжки', cal: 280 },
            'shchi': { name: 'Щі', cal: 45 },
            'ukha': { name: 'Уха', cal: 40 },
            'beef stroganoff': { name: 'Бефстроганов', cal: 180 },
            'olivier': { name: 'Олів\'є', cal: 150 },
            'vinegret': { name: 'Вінегрет', cal: 110 },
            'solyanka': { name: 'Солянка', cal: 70',
            
            // Італійська
            'risotto': { name: 'Різотто', cal: 120 },
            'osso buco': { name: 'Оссо Буко', cal: 200 },
            'carbonara': { name: 'Карбонара', cal: 190 },
            'amatriciana': { name: 'Аматрічана', cal: 160 },
            'cacio e pepe': { name: 'Качо е Пепе', cal: 180 },
            'gnocchi': { name: 'Ньоккі', cal: 133 },
            'minestrone': { name: 'Мінестроне', cal: 82 },
            'bruschetta': { name: 'Брускетта', cal: 160 },
            'caprese': { name: 'Капрезе', cal: 160 },
            'prosciutto': { name: 'Прошутто', cal: 250 },
            'parmigiana': { name: 'Парміджана', cal: 160',
            
            // Японська
            'tempura': { name: 'Темпура', cal: 227 },
            'teriyaki': { name: 'Теріякі', cal: 180 },
            'yakitori': { name: 'Якіторі', cal: 170 },
            'tonkatsu': { name: 'Тонкацу', cal: 250 },
            'okonomiyaki': { name: 'Окономіякі', cal: 180 },
            'takoyaki': { name: 'Такоякі', cal: 200 },
            'udon': { name: 'Удон', cal: 140 },
            'soba': { name: 'Соба', cal: 130 },
            'miso soup': { name: 'Місо-суп', cal: 42',
            
            // Корейська
            'bibimbap': { name: 'Бібімбап', cal: 180 },
            'bulgogi': { name: 'Бульгогі', cal: 200 },
            'galbi': { name: 'Гальбі', cal: 220 },
            'tteokbokki': { name: 'Ттокбоккі', cal: 200 },
            'japchae': { name: 'Япчхе', cal: 160 },
            'kimchi': { name: 'Кімчі', cal: 23 },
            'jjigae': { name: 'Чіге', cal: 80 },
            'samgyeopsal': { name: 'Самгйопсаль', cal: 260',
            
            // Китайська
            'dim sum': { name: 'Дім-сам', cal: 150 },
            'congee': { name: 'Конджі', cal: 60 },
            'char siu': { name: 'Ча-сіу', cal: 220 },
            'kung pao': { name: 'Кунг-пао', cal: 180 },
            'mapo tofu': { name: 'Мапо тофу', cal: 130 },
            'wonton soup': { name: 'Суп з вонтоном', cal: 110 },
            'hot and sour soup': { name: 'Гостро-кислий суп', cal: 80 },
            'egg drop soup': { name: 'Суп з яйцем', cal: 65',
            
            // Вietnamese
            'pho': { name: 'Фо', cal: 120 },
            'banh mi': { name: 'Бань-мі', cal: 200 },
            'bun cha': { name: 'Бун Ча', cal: 180 },
            'goi cuon': { name: 'Гой Куон', cal: 120 },
            'com tam': { name: 'Ком Там', cal: 190 },
            'bun bo hue': { name: 'Бун Бо Хюе', cal: 150',
            
            // Thai
            'pad thai': { name: 'Пад Тай', cal: 190 },
            'green curry': { name: 'Зелене каррі', cal: 120 },
            'red curry': { name: 'Червоне каррі', cal: 130 },
            'massaman': { name: 'Массаман', cal: 140 },
            'tom yum': { name: 'Том Ям', cal: 80 },
            'tom kha': { name: 'Том Кха', cal: 90 },
            'som tam': { name: 'Сом Там', cal: 90 },
            'larb': { name: 'Ларб', cal: 150 },
            'pad see ew': { name: 'Пад Сі Іу', cal: 170 },
            'pad kepao': { name: 'Пад Кепао', cal: 160',
            
            // Indian
            'butter chicken': { name: 'Курка в маслі', cal: 190 },
            'tikka masala': { name: 'Тіка Масала', cal: 160 },
            'biryani': { name: 'Бір\'яні', cal: 180 },
            'dal': { name: 'Дал', cal: 120 },
            'samosa': { name: 'Самоса', cal: 260 },
            'naan': { name: 'Наан', cal: 310 },
            'palak paneer': { name: 'Палак Панір', cal: 140 },
            'chana masala': { name: 'Чана Масала', cal: 150 },
            'rogan josh': { name: 'Роган-джош', cal: 170 },
            'vindaloo': { name: 'Віндалу', cal: 160 },
            'korma': { name: 'Корма', cal: 150 },
            'tandoori': { name: 'Тандурі', cal: 180 },
            'pakora': { name: 'Пакора', cal: 250 },
            'chai': { name: 'Чай', cal: 50',
            
            // Middle Eastern
            'hummus': { name: 'Хумус', cal: 166 },
            'falafel': { name: 'Фалафель', cal: 333 },
            'shawarma': { name: 'Шаварма', cal: 230 },
            'kebab': { name: 'Кебаб', cal: 279 },
            'tabbouleh': { name: 'Таббуле', cal: 100 },
            'baba ganoush': { name: 'Баба-гануш', cal: 130 },
            'fattoush': { name: 'Фаттуш', cal: 90 },
            'manakish': { name: 'Манакіш', cal: 250 },
            'fatayer': { name: 'Фатайєр', cal: 200 },
            'kibbeh': { name: 'Кіббех', cal: 220 },
            'mansaf': { name: 'Мансаф', cal: 200 },
            'ful medames': { name: 'Фуль Медамес', cal: 180',
            
            // Mexican
            'taco': { name: 'Тако', cal: 210 },
            'burrito': { name: 'Бурріто', cal: 206 },
            'quesadilla': { name: 'Кесаділья', cal: 227 },
            'enchilada': { name: 'Енчілада', cal: 190 },
            'tostada': { name: 'Тостада', cal: 180 },
            'chimichanga': { name: 'Чимічанга', cal: 240 },
            'empanada': { name: 'Емпанада', cal: 250 },
            'tamale': { name: 'Тамале', cal: 220 },
            'chile relleno': { name: 'Чиле Реллено', cal: 200 },
            'pozole': { name: 'Позоле', cal: 120 },
            'mole': { name: 'Моле', cal: 180 },
            'elote': { name: 'Елоте', cal: 150 },
            'nachos': { name: 'Начос', cal: 316 },
            'guacamole': { name: 'Гуакамоле', cal: 151 },
            'salsa': { name: 'Сальса', cal: 36 },
            'churros': { name: 'Чуррос', cal: 350 },
            'horchata': { name: 'Орчата', cal: 120 },
            'agua fresca': { name: 'Агуа Фреска', cal: 60',
            
            // Greek
            'moussaka': { name: 'Мусака', cal: 130 },
            'spanakopita': { name: 'Спанакопіта', cal: 230 },
            'souvlaki': { name: 'Сувлакі', cal: 220 },
            'gyro': { name: 'Гірос', cal: 215 },
            'tzatziki': { name: 'Цацикі', cal: 100 },
            'dolma': { name: 'Долма', cal: 120 },
            'pastitsio': { name: 'Пастиціо', cal: 150 },
            'gemista': { name: 'Джеміста', cal: 100 },
            'tiropita': { name: 'Тіропіта', cal: 250 },
            'baklava': { name: 'Баклава', cal: 527 },
            'galaktoboureko': { name: 'Галактобуреко', cal: 300',
            
            // Spanish
            'paella': { name: 'Паелья', cal: 172 },
            'tortilla': { name: 'Тортілья', cal: 150 },
            'churros': { name: 'Чуррос', cal: 350 },
            'gazpacho': { name: 'Гаспачо', cal: 40 },
            'croquetas': { name: 'Крокетас', cal: 200 },
            'patatas bravas': { name: 'Пататас Бравас', cal: 180 },
            'pulpo a la gallega': { name: 'Пульпо', cal: 120 },
            'jamón': { name: 'Хамон', cal: 250 },
            'pimientos de padrón': { name: 'Пім\'єнто', cal: 25 },
            'pan con tomate': { name: 'Пан кон Томате', cal: 150',
            
            // German
            'sauerkraut': { name: 'Квашена капуста', cal: 20 },
            'bratwurst': { name: 'Братвурст', cal: 300 },
            'pretzel': { name: 'Брецель', cal: 250 },
            'schnitzel': { name: 'Шніцель', cal: 300 },
            'spätzle': { name: 'Шпецле', cal: 150 },
            'kartoffelpuffer': { name: 'Картопляні оладки', cal: 200 },
            'eintopf': { name: 'Ейнтопф', cal: 80 },
            'rouladen': { name: 'Руладен', cal: 200 },
            'strudel': { name: 'Струдель', cal: 270 },
            'black forest cake': { name: 'Чорний ліс', cal: 340',
            
            // French
            'croissant': { name: 'Круассан', cal: 406 },
            'baguette': { name: 'Багет', cal: 270 },
            'crepe': { name: 'Креп', cal: 167 },
            'quiche': { name: 'Кіш', cal: 200 },
            'ratatouille': { name: 'Рататуй', cal: 80 },
            'coq au vin': { name: 'Кок-о-Вен', cal: 180 },
            'beef bourguignon': { name: 'Беф-Бургіньйон', cal: 200 },
            'onion soup': { name: 'Цибулевий суп', cal: 48 },
            'crème brûlée': { name: 'Крем-брюле', cal: 350 },
            'tarte tatin': { name: 'Тарт Татен', cal: 280 },
            'macarons': { name: 'Макарони', cal: 350 },
            'éclair': { name: 'Еклер', cal: 320 },
            'profiterole': { name: 'Профітроль', cal: 300',
            
            // Italian
            'pizza margherita': { name: 'Маргарита', cal: 250 },
            'pasta carbonara': { name: 'Карбонара', cal: 190 },
            'lasagna': { name: 'Лазанья', cal: 135 },
            'risotto': { name: 'Різотто', cal: 120 },
            'bruschetta': { name: 'Брускетта', cal: 160 },
            'caprese salad': { name: 'Капрезе', cal: 160 },
            'minestrone': { name: 'Мінестроне', cal: 82 },
            'osso buco': { name: 'Оссо Буко', cal: 200 },
            'tiramisu': { name: 'Тірамісу', cal: 250 },
            'panna cotta': { name: 'Панна-котта', cal: 310 },
            'gelato': { name: 'Джелато', cal: 191 },
            'prosciutto': { name: 'Прошутто', cal: 250 },
            'mozzarella': { name: 'Моцарелла', cal: 280 },
            'parmesan': { name: 'Пармезан', cal: 431 },
            'basil': { name: 'Базилік', cal: 23 },
            'olive oil': { name: 'Оливкова олія', cal: 884',
            
            // Japanese
            'sushi': { name: 'Суші', cal: 143 },
            'sashimi': { name: 'Сашимі', cal: 143 },
            'tempura': { name: 'Темпура', cal: 227 },
            'teriyaki': { name: 'Теріякі', cal: 180 },
            'ramen': { name: 'Рамен', cal: 191 },
            'udon': { name: 'Удон', cal: 140 },
            'soba': { name: 'Соба', cal: 130 },
            'miso soup': { name: 'Місо-суп', cal: 42 },
            'edamame': { name: 'Едамаме', cal: 121 },
            'gyoza': { name: 'Ґйоза', cal: 200 },
            'tonkatsu': { name: 'Тонкацу', cal: 250 },
            'katsu curry': { name: 'Кацу Каррі', cal: 220 },
            'okonomiyaki': { name: 'Окономіякі', cal: 180 },
            'takoyaki': { name: 'Такоякі', cal: 200 },
            'yakitori': { name: 'Якіторі', cal: 170 },
            'onigiri': { name: 'Оніґірі', cal: 180 },
            'bento': { name: 'Бенто', cal: 500 },
            'matcha': { name: 'Матча', cal: 3 },
            'mochi': { name: 'Мочі', cal: 250',
            
            // Korean
            'bibimbap': { name: 'Бібімбап', cal: 180 },
            'bulgogi': { name: 'Бульгогі', cal: 200 },
            'galbi': { name: 'Гальбі', cal: 220 },
            'tteokbokki': { name: 'Ттокбоккі', cal: 200 },
            'japchae': { name: 'Япчхе', cal: 160 },
            'kimchi': { name: 'Кімчі', cal: 23 },
            'jjigae': { name: 'Чіге', cal: 80 },
            'samgyeopsal': { name: 'Самгйопсаль', cal: 260 },
            'kimbap': { name: 'Кімбап', cal: 200 },
            'hotteok': { name: 'Хотток', cal: 250 },
            'tteok': { name: 'Тток', cal: 200 },
            'soju': { name: 'Соджу', cal: 148',
            
            // Chinese
            'dim sum': { name: 'Дім-сам', cal: 150 },
            'congee': { name: 'Конджі', cal: 60 },
            'char siu': { name: 'Ча-сіу', cal: 220 },
            'kung pao chicken': { name: 'Кунг-пао', cal: 180 },
            'mapo tofu': { name: 'Мапо тофу', cal: 130 },
            'wonton soup': { name: 'Суп з вонтоном', cal: 110 },
            'hot and sour soup': { name: 'Гостро-кислий суп', cal: 80 },
            'egg drop soup': { name: 'Суп з яйцем', cal: 65 },
            'peking duck': { name: 'Пекінська качка', cal: 337 },
            'spring rolls': { name: 'Літні роли', cal: 149 },
            'dumplings': { name: 'Пельмені', cal: 200 },
            'chow mein': { name: 'Чоу мейн', cal: 180 },
            'lo mein': { name: 'Ло мейн', cal: 170 },
            'fried rice': { name: 'Смажений рис', cal: 163 },
            'general tso chicken': { name: 'Дженерал Цо', cal: 200 },
            'orange chicken': { name: 'Апельсинова курка', cal: 220 },
            'sweet and sour pork': { name: 'Кисло-солодка свинина', cal: 220 },
            'ma po tofu': { name: 'Мапо тофу', cal: 130 },
            'xiao long bao': { name: 'Сяо Лун Бао', cal: 200 },
            'zi char': { name: 'Цзи Ча', cal: 180',
            
            // Vietnamese
            'pho': { name: 'Фо', cal: 120 },
            'banh mi': { name: 'Бань-мі', cal: 200 },
            'bun cha': { name: 'Бун Ча', cal: 180 },
            'goi cuon': { name: 'Гой Куон', cal: 120 },
            'com tam': { name: 'Ком Там', cal: 190 },
            'bun bo hue': { name: 'Бун Бо Хюе', cal: 150 },
            'banh xeo': { name: 'Бань Сео', cal: 180 },
            'ca kho to': { name: 'Ка Ко То', cal: 160 },
            'cha ca': { name: 'Ча Ка', cal: 150 },
            'bun rieu': { name: 'Бун Рieu', cal: 130',
            
            // Thai
            'pad thai': { name: 'Пад Тай', cal: 190 },
            'green curry': { name: 'Зелене каррі', cal: 120 },
            'red curry': { name: 'Червоне каррі', cal: 130 },
            'massaman curry': { name: 'Массаман', cal: 140 },
            'tom yum': { name: 'Том Ям', cal: 80 },
            'tom kha gai': { name: 'Том Кха Гай', cal: 90 },
            'som tam': { name: 'Сом Там', cal: 90 },
            'larb': { name: 'Ларб', cal: 150 },
            'pad see ew': { name: 'Пад Сі Іу', cal: 170 },
            'pad kra pao': { name: 'Пад Кепао', cal: 160 },
            'khao soi': { name: 'Кхао Сой', cal: 180 },
            'mango sticky rice': { name: 'Манго з рисом', cal: 250 },
            'thai iced tea': { name: 'Тайський чай', cal: 80',
            
            // Indian
            'butter chicken': { name: 'Курка в маслі', cal: 190 },
            'chicken tikka masala': { name: 'Тіка Масала', cal: 160 },
            'biryani': { name: 'Бір\'яні', cal: 180 },
            'dal': { name: 'Дал', cal: 120 },
            'samosa': { name: 'Самоса', cal: 260 },
            'naan': { name: 'Наан', cal: 310 },
            'palak paneer': { name: 'Палак Панір', cal: 140 },
            'chana masala': { name: 'Чана Масала', cal: 150 },
            'rogan josh': { name: 'Роган-джош', cal: 170 },
            'vindaloo': { name: 'Віндалу', cal: 160 },
            'korma': { name: 'Корма', cal: 150 },
            'tandoori chicken': { name: 'Тандурі', cal: 180 },
            'pakora': { name: 'Пакора', cal: 250 },
            'chai': { name: 'Чай', cal: 50 },
            'masala chai': { name: 'Масала Чай', cal: 70 },
            'mango lassi': { name: 'Манго Лассі', cal: 120 },
            'gulab jamun': { name: 'Гулаб Джамун', cal: 350 },
            'jalebi': { name: 'Джалебі', cal: 400 },
            'kheer': { name: 'Кхір', cal: 150 },
            'paneer tikka': { name: 'Панір Тіка', cal: 200 },
            'aloo gobi': { name: 'Алу Гобі', cal: 120 },
            'saag': { name: 'Сааг', cal: 100 },
            'raita': { name: 'Райта', cal: 60',
            
            // Middle Eastern
            'hummus': { name: 'Хумус', cal: 166 },
            'falafel': { name: 'Фалафель', cal: 333 },
            'shawarma': { name: 'Шаварма', cal: 230 },
            'kebab': { name: 'Кебаб', cal: 279 },
            'tabbouleh': { name: 'Таббуле', cal: 100 },
            'baba ganoush': { name: 'Баба-гануш', cal: 130 },
            'fattoush': { name: 'Фаттуш', cal: 90 },
            'manakish': { name: 'Манакіш', cal: 250 },
            'fatayer': { name: 'Фатайєр', cal: 200 },
            'kibbeh': { name: 'Кіббех', cal: 220 },
            'mansaf': { name: 'Мансаф', cal: 200 },
            'ful medames': { name: 'Фуль Медамес', cal: 180 },
            'lahmacun': { name: 'Лахмаджун', cal: 220 },
            'pide': { name: 'Піде', cal: 250 },
            'baklava': { name: 'Баклава', cal: 527 },
            'kunafa': { name: 'Кунафа', cal: 350 },
            'baklava': { name: 'Баклава', cal: 527',
            
            // Misc/common
            'sandwich': { name: 'Сендвіч', cal: 252 },
            'wrap': { name: 'Рол', cal: 230 },
            'soup': { name: 'Суп', cal: 50 },
            'salad': { name: 'Салат', cal: 20 },
            'stew': { name: 'Тушковане', cal: 80 },
            'curry': { name: 'Каррі', cal: 125 },
            'stir fry': { name: 'Смажені овочі', cal: 110 },
            'grilled': { name: 'Смажене', cal: 180 },
            'roasted': { name: 'Запечене', cal: 170 },
            'fried': { name: 'Смажене', cal: 200 },
            'baked': { name: 'Запечене', cal: 160 },
            'steamed': { name: 'На пару', cal: 100 },
            'boiled': { name: 'Варене', cal: 80 },
            'raw': { name: 'Сире', cal: 60 },
            'breakfast': { name: 'Сніданок', cal: 300 },
            'lunch': { name: 'Обід', cal: 400 },
            'dinner': { name: 'Вечеря', cal: 500 },
            'snack': { name: 'Перекус', cal: 150 },
            'dessert': { name: 'Десерт', cal: 300 },
            'appetizer': { name: 'Закуска', cal: 150 },
            'main course': { name: 'Основна страва', cal: 400 },
            'side dish': { name: 'Гарнір', cal: 150 },
            'drink': { name: 'Напій', cal: 80 },
            'beverage': { name: 'Напій', cal: 80 },
            'alcohol': { name: 'Алкоголь', cal: 150 },
            'non-alcoholic': { name: 'Безалкогольний', cal: 50 },
            'vegetarian': { name: 'Вегетаріанське', cal: 200 },
            'vegan': { name: 'Веганське', cal: 180 },
            'gluten-free': { name: 'Без глютену', cal: 200 },
            'dairy-free': { name: 'Без молочного', cal: 180 },
            'healthy': { name: 'Корисне', cal: 150 },
            'junk food': { name: 'Фастфуд', cal: 400 },
            'fast food': { name: 'Фастфуд', cal: 400 },
            'comfort food': { name: 'Домашня їжа', cal: 350 },
            'street food': { name: 'Вулична їжа', cal: 300 },
            'homemade': { name: 'Домашнє', cal: 250 },
            'restaurant': { name: 'Ресторанне', cal: 400 },
            'takeout': { name: 'На винос', cal: 450 },
            'leftovers': { name: 'Залишки', cal: 300 },
            'frozen': { name: 'Заморожене', cal: 250 },
            'canned': { name: 'Консерви', cal: 200 },
            'dried': { name: 'Сухе', cal: 300 },
            'fresh': { name: 'Свіже', cal: 100 },
            'processed': { name: 'Оброблене', cal: 250 },
            'organic': { name: 'Органічне', cal: 200 },
            'natural': { name: 'Натуральне', cal: 180 },
            'whole': { name: 'Ціле', cal: 200 },
            'sliced': { name: 'Нарізане', cal: 150 },
            'chopped': { name: 'Нарізане', cal: 150 },
            'diced': { name: 'Кубиками', cal: 150 },
            'minced': { name: 'Фарш', cal: 200 },
            'ground': { name: 'Фарш', cal: 200 },
            'shredded': { name: 'Терте', cal: 120 },
            'grated': { name: 'Терте', cal: 120 },
            'mashed': { name: 'Пюре', cal: 100 },
            'pureed': { name: 'Пюре', cal: 100 },
            'blended': { name: 'Змішане', cal: 100 },
            'mixed': { name: 'Змішане', cal: 150 },
            'combined': { name: 'Змішане', cal: 150 },
            'assorted': { name: 'Асорті', cal: 200 },
            'variety': { name: 'Асорті', cal: 200 },
            'platter': { name: 'Тарілка', cal: 400 },
            'plate': { name: 'Тарілка', cal: 350 },
            'bowl': { name: 'Чаша', cal: 300 },
            'cup': { name: 'Чашка', cal: 200 },
            'glass': { name: 'Склянка', cal: 150 },
            'mug': { name: 'Кухоль', cal: 200 },
            'bottle': { name: 'Пляшка', cal: 250 },
            'can': { name: 'Банка', cal: 150 },
            'packet': { name: 'Пачка', cal: 200 },
            'bag': { name: 'Пакет', cal: 300 },
            'box': { name: 'Коробка', cal: 400 },
            'basket': { name: 'Кошик', cal: 500 },
            'tray': { name: 'Піднос', cal: 600 },
            'dish': { name: 'Страва', cal: 300 },
            'meal': { name: 'Прийом їжі', cal: 400 },
            'food': { name: 'Їжа', cal: 250 },
            'eating': { name: 'Їжа', cal: 250 },
            'dining': { name: 'Їжа', cal: 300 },
            'cooking': { name: 'Готування', cal: 200 },
            'baking': { name: 'Випічка', cal: 250 },
            'grilling': { name: 'На грилі', cal: 200 },
            'frying': { name: 'Смаження', cal: 220 },
            'boiling': { name: 'Варіння', cal: 100 },
            'steaming': { name: 'На пару', cal: 100 },
            'roasting': { name: 'Запікання', cal: 180 },
            'broiling': { name: 'Бройлер', cal: 200 },
            'sauteing': { name: 'Обсмажування', cal: 180 },
            'simmering': { name: 'Тушкування', cal: 120 },
            'braising': { name: 'Тушкування', cal: 150 },
            'poaching': { name: 'Варіння', cal: 100 },
            'deep frying': { name: 'У фритюрі', cal: 300 },
            'air frying': { name: 'У air fryer', cal: 150 },
            'microwaving': { name: 'У мікрохвильовці', cal: 120 },
            'raw food': { name: 'Сира їжа', cal: 80 },
            'cooked': { name: 'Приготоване', cal: 200 },
            'uncooked': { name: 'Сире', cal: 80 },
            'undercooked': { name: 'Недоварене', cal: 150 },
            'overcooked': { name: 'Переварене', cal: 180 },
            'burnt': { name: 'Підгоріле', cal: 160 },
            'charred': { name: 'Обвуглене', cal: 170 },
            'crispy': { name: 'Хрустке', cal: 220 },
            'crunchy': { name: 'Хрустке', cal: 200 },
            'soft': { name: 'М\'яке', cal: 150 },
            'tender': { name: 'Ніжне', cal: 180 },
            'chewy': { name: 'Жуйке', cal: 200 },
            'mushy': { name: 'Кашоподібне', cal: 120 },
            'soggy': { name: 'Мокре', cal: 100 },
            'dry': { name: 'Сухе', cal: 180 },
            'moist': { name: 'Вологе', cal: 160 },
            'juicy': { name: 'Соковите', cal: 140 },
            'bland': { name: 'Нудне', cal: 120 },
            'flavorful': { name: 'Смачне', cal: 180 },
            'spicy': { name: 'Гостре', cal: 150 },
            'sweet': { name: 'Солодке', cal: 200 },
            'sour': { name: 'Кисле', cal: 100 },
            'salty': { name: 'Солоне', cal: 120 },
            'bitter': { name: 'Гірке', cal: 80 },
            'umami': { name: 'Умамі', cal: 150 },
            'savory': { name: 'Смачне', cal: 180 },
            'delicious': { name: 'Смачне', cal: 200 },
            'tasty': { name: 'Смачне', cal: 200 },
            'yummy': { name: 'Смачне', cal: 200 },
            'appetizing': { name: 'Апетитне', cal: 180 },
            'mouthwatering': { name: 'Апетитне', cal: 200 },
            'delectable': { name: 'Чудове', cal: 220 },
            'scrumptious': { name: 'Чудове', cal: 250 },
            'divine': { name: 'Божественне', cal: 300 },
            'heavenly': { name: 'Небесне', cal: 350 },
            'sublime': { name: 'Піднесене', cal: 300 },
            'exquisite': { name: 'Вишукане', cal: 280 },
            'gourmet': { name: 'Гурме', cal: 350 },
            'gastropub': { name: 'Гастропаб', cal: 400 },
            'fine dining': { name: 'Вишукане харчування', cal: 500 },
            'casual dining': { name: 'Кафе', cal: 400 },
            'fast casual': { name: 'Швидке кафе', cal: 450 },
            'quick service': { name: 'Швидке обслуговування', cal: 500 },
            'food truck': { name: 'Фуд-трак', cal: 400 },
            'food stall': { name: 'Стійка', cal: 300 },
            'food court': { name: 'Фуд-корт', cal: 450 },
            'buffet': { name: 'Бюфет', cal: 600 },
            'all you can eat': { name: 'Скільки з\'їси', cal: 800 },
            'family style': { name: 'Сімейний формат', cal: 500 },
            'plated': { name: 'На тарілці', cal: 400 },
            'family style': { name: 'Сімейний формат', cal: 500 },
            'plated': { name: 'На тарілці', cal: 400 },
            'family style': { name: 'Сімейний формат', cal: 500 },
            'plated': { name: 'На тарілці', cal: 400 }
        };
        
        // Обробка результату
        if (data && typeof data === 'object') {
            // Якщо це VLM відповідь з JSON
            if (data.food_items || data.food_items === []) {
                const items = data.food_items || [];
                const drinks = data.drink_items || [];
                const allItems = [...items, ...drinks];
                
                if (allItems.length > 0) {
                    const dishes = allItems.map(item => {
                        const itemLower = item.toLowerCase();
                        const foodInfo = calorieDB[itemLower] || { name: item, cal: 150 };
                        return {
                            name: foodInfo.name,
                            calories: foodInfo.cal,
                            confidence: 85
                        };
                    });
                    
                    const totalCal = dishes.reduce((sum, d) => sum + d.calories, 0);
                    
                    return res.status(200).json({
                        success: true,
                        dishes: dishes,
                        totalCalories: totalCal,
                        title: data.image_title || 'Їжа'
                    });
                }
            }
            
            // Якщо це класифікація з信心
            if (Array.isArray(data) && data.length > 0) {
                const topResults = data.slice(0, 3).map(item => {
                    const itemLabel = item.label ? item.label.toLowerCase() : '';
                    const foodInfo = calorieDB[itemLabel] || { name: item.label || 'Їжа', cal: 200 };
                    return {
                        name: foodInfo.name,
                        confidence: Math.round((item.score || 0.5) * 100),
                        calories: foodInfo.cal
                    };
                });
                
                return res.status(200).json({
                    success: true,
                    dishes: topResults,
                    totalCalories: topResults[0].calories
                });
            }
        }
        
        return res.status(200).json({
            success: false,
            error: 'Не вдалося розпізнати'
        });
        
    } catch (error) {
        return res.status(500).json({ error: error.message });
    }
};
