const fetch = require('node-fetch');

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    
    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }
    
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }
    
    try {
        const { image } = req.body;
        
        if (!image) {
            return res.status(400).json({ error: 'No image provided' });
        }
        
        const hfToken = process.env.HF_TOKEN;
        
        if (!hfToken) {
            return res.status(500).json({ error: 'HF_TOKEN not configured' });
        }
        
        // Обробляємо зображення
        let imageBase64 = image;
        if (image.includes('base64,')) {
            imageBase64 = image.split('base64,')[1];
        }
        
        const imageBuffer = Buffer.from(imageBase64, 'base64');
        
        // Використовуємо nateraw/food модель
        const response = await fetch(
            'https://router.huggingface.co/hf-inference/models/nateraw/food',
            {
                method: 'POST',
                headers: {
                    'Authorization': 'Bearer ' + hfToken,
                    'Content-Type': 'application/octet-stream'
                },
                body: imageBuffer,
                timeout: 60000
            }
        );
        
        const data = await response.json();
        
        // Розширена база калорій (101 категорія Food-101)
        const calorieDB = {
            // М'ясо та ковбаси
            'sausage': { name: 'Сосиска', cal: 275, emoji: '🌭' },
            'hot_dog': { name: 'Хот-дог', cal: 290, emoji: '🌭' },
            'hot dog': { name: 'Хот-дог', cal: 290, emoji: '🌭' },
            'bacon': { name: 'Бекон', cal: 541, emoji: '🥓' },
            'ham': { name: 'Шинка', cal: 145, emoji: '🍖' },
            
            // Овочі
            'tomato': { name: 'Помідор', cal: 18, emoji: '🍅' },
            'tomatoes': { name: 'Помідори', cal: 18, emoji: '🍅' },
            'cucumber': { name: 'Огірок', cal: 15, emoji: '🥒' },
            'carrot': { name: 'Морква', cal: 41, emoji: '🥕' },
            'carrots': { name: 'Морква', cal: 41, emoji: '🥕' },
            'onion': { name: 'Цибуля', cal: 40, emoji: '🧅' },
            'potato': { name: 'Картопля', cal: 95, emoji: '🥔' },
            'potatoes': { name: 'Картопля', cal: 95, emoji: '🥔' },
            'pepper': { name: 'Перець', cal: 27, emoji: '🫑' },
            'lettuce': { name: 'Салат', cal: 15, emoji: '🥬' },
            'salad': { name: 'Салат', cal: 20, emoji: '🥗' },
            'broccoli': { name: 'Броколі', cal: 34, emoji: '🥦' },
            'mushroom': { name: 'Гриби', cal: 22, emoji: '🍄' },
            'mushrooms': { name: 'Гриби', cal: 22, emoji: '🍄' },
            'corn': { name: 'Кукурудза', cal: 86, emoji: '🌽' },
            'avocado': { name: 'Авокадо', cal: 160, emoji: '🥑' },
            'spinach': { name: 'Шпинат', cal: 23, emoji: '🥬' },
            'peas': { name: 'Горох', cal: 81, emoji: '🟢' },
            'beans': { name: 'Квасоля', cal: 127, emoji: '🫘' },
            
            // Фрукти
            'apple': { name: 'Яблуко', cal: 52, emoji: '🍎' },
            'apples': { name: 'Яблука', cal: 52, emoji: '🍎' },
            'banana': { name: 'Банан', cal: 95, emoji: '🍌' },
            'bananas': { name: 'Банани', cal: 95, emoji: '🍌' },
            'orange': { name: 'Апельсин', cal: 43, emoji: '🍊' },
            'oranges': { name: 'Апельсини', cal: 43, emoji: '🍊' },
            'grape': { name: 'Виноград', cal: 69, emoji: '🍇' },
            'grapes': { name: 'Виноград', cal: 69, emoji: '🍇' },
            'strawberry': { name: 'Полуниця', cal: 33, emoji: '🍓' },
            'strawberries': { name: 'Полуниця', cal: 33, emoji: '🍓' },
            'blueberry': { name: 'Чорниця', cal: 57, emoji: '🫐' },
            'blueberries': { name: 'Чорниця', cal: 57, emoji: '🫐' },
            'peach': { name: 'Персик', cal: 40, emoji: '🍑' },
            'pear': { name: 'Груша', cal: 57, emoji: '🍐' },
            'mango': { name: 'Манго', cal: 60, emoji: '🥭' },
            'pineapple': { name: 'Ананас', cal: 50, emoji: '🍍' },
            'watermelon': { name: 'Кавун', cal: 30, emoji: '🍉' },
            'kiwi': { name: 'Ківі', cal: 61, emoji: '🥝' },
            'lemon': { name: 'Лимон', cal: 29, emoji: '🍋' },
            'cherry': { name: 'Вишня', cal: 50, emoji: '🍒' },
            'cherries': { name: 'Вишня', cal: 50, emoji: '🍒' },
            'pomegranate': { name: 'Гранат', cal: 83, emoji: '🍎' },
            'coconut': { name: 'Кокос', cal: 354, emoji: '🥥' },
            'olives': { name: 'Оливки', cal: 115, emoji: '🫒' },
            
            // Молочні
            'cheese': { name: 'Сир', cal: 350, emoji: '🧀' },
            'cheddar': { name: 'Чеддер', cal: 403, emoji: '🧀' },
            'mozzarella': { name: 'Моцарелла', cal: 280, emoji: '🧀' },
            'parmesan': { name: 'Пармезан', cal: 431, emoji: '🧀' },
            'feta': { name: 'Фета', cal: 264, emoji: '🧀' },
            'yogurt': { name: 'Йогурт', cal: 60, emoji: '🥛' },
            'milk': { name: 'Молоко', cal: 42, emoji: '🥛' },
            'cream': { name: 'Вершки', cal: 195, emoji: '🥛' },
            'butter': { name: 'Масло', cal: 717, emoji: '🧈' },
            'ice_cream': { name: 'Морозиво', cal: 207, emoji: '🍨' },
            'ice cream': { name: 'Морозиво', cal: 207, emoji: '🍨' },
            
            // Хліб та випічка
            'bread': { name: 'Хліб', cal: 265, emoji: '🍞' },
            'toast': { name: 'Тост', cal: 260, emoji: '🍞' },
            'croissant': { name: 'Круассан', cal: 406, emoji: '🥐' },
            'muffin': { name: 'Маффін', cal: 340, emoji: '🧁' },
            'pancake': { name: 'Млинець', cal: 227, emoji: '🥞' },
            'pancakes': { name: 'Млинці', cal: 227, emoji: '🥞' },
            'waffle': { name: 'Вафля', cal: 291, emoji: '🧇' },
            'donut': { name: 'Пончик', cal: 452, emoji: '🍩' },
            'cookies': { name: 'Печиво', cal: 488, emoji: '🍪' },
            'cookie': { name: 'Печиво', cal: 488, emoji: '🍪' },
            'bagel': { name: 'Бейгл', cal: 250, emoji: '🥯' },
            'pretzel': { name: 'Брецель', cal: 250, emoji: '🥨' },
            'baguette': { name: 'Багет', cal: 270, emoji: '🥖' },
            'roll': { name: 'Булка', cal: 320, emoji: '🍞' },
            'bun': { name: 'Булочка', cal: 310, emoji: '🍞' },
            'tortilla': { name: 'Тортилья', cal: 237, emoji: '🫓' },
            'pita': { name: 'Піта', cal: 275, emoji: '🫓' },
            'naan': { name: 'Наан', cal: 310, emoji: '🫓' },
            'scone': { name: 'Скон', cal: 340, emoji: '🍞' },
            'crackers': { name: 'Сухарики', cal: 502, emoji: '🍘' },
            
            // М'ясо
            'chicken': { name: 'Курка', cal: 239, emoji: '🍗' },
            'chicken_breast': { name: 'Куряча грудка', cal: 165, emoji: '🍗' },
            'chicken_wing': { name: 'Куряче крило', cal: 203, emoji: '🍗' },
            'beef': { name: 'Яловичина', cal: 250, emoji: '🥩' },
            'steak': { name: 'Стейк', cal: 271, emoji: '🥩' },
            'pork': { name: 'Свинина', cal: 242, emoji: '🥩' },
            'lamb': { name: 'Баранина', cal: 294, emoji: '🥩' },
            'turkey': { name: 'Індичка', cal: 135, emoji: '🦃' },
            'duck': { name: 'Качка', cal: 337, emoji: '🦆' },
            'meatball': { name: 'Котлета', cal: 250, emoji: '🧆' },
            'meatballs': { name: 'Котлети', cal: 250, emoji: '🧆' },
            'ribs': { name: 'Реберця', cal: 285, emoji: '🍖' },
            
            // Бургери
            'hamburger': { name: 'Бургер', cal: 295, emoji: '🍔' },
            'burger': { name: 'Бургер', cal: 295, emoji: '🍔' },
            'cheeseburger': { name: 'Чізбургер', cal: 354, emoji: '🍔' },
            
            // Риба та морепродукти
            'salmon': { name: 'Лосось', cal: 208, emoji: '🐟' },
            'tuna': { name: 'Тунець', cal: 132, emoji: '🐟' },
            'shrimp': { name: 'Креветки', cal: 99, emoji: '🦐' },
            'crab': { name: 'Краб', cal: 97, emoji: '🦀' },
            'lobster': { name: 'Лангуст', cal: 89, emoji: '🦞' },
            'fish': { name: 'Риба', cal: 206, emoji: '🐟' },
            'sushi': { name: 'Суші', cal: 143, emoji: '🍣' },
            'sashimi': { name: 'Сашимі', cal: 143, emoji: '🍣' },
            
            // Готові страви
            'pizza': { name: 'Піца', cal: 266, emoji: '🍕' },
            'pepperoni_pizza': { name: 'Піца з пепероні', cal: 311, emoji: '🍕' },
            'cheese_pizza': { name: 'Сирна піца', cal: 272, emoji: '🍕' },
            'margherita': { name: 'Маргарита', cal: 250, emoji: '🍕' },
            'pasta': { name: 'Паста', cal: 131, emoji: '🍝' },
            'spaghetti': { name: 'Спагетті', cal: 158, emoji: '🍝' },
            'lasagna': { name: 'Лазанья', cal: 135, emoji: '🍝' },
            'noodles': { name: 'Локшина', cal: 138, emoji: '🍜' },
            'ramen': { name: 'Рамен', cal: 191, emoji: '🍜' },
            'rice': { name: 'Рис', cal: 130, emoji: '🍚' },
            'fried_rice': { name: 'Смажений рис', cal: 163, emoji: '🍚' },
            'curry': { name: 'Каррі', cal: 125, emoji: '🍛' },
            'soup': { name: 'Суп', cal: 50, emoji: '🍲' },
            'stew': { name: 'Тушковане', cal: 80, emoji: '🍲' },
            'sandwich': { name: 'Сендвіч', cal: 252, emoji: '🥪' },
            'wrap': { name: 'Рол', cal: 230, emoji: '🌯' },
            'burrito': { name: 'Бурріто', cal: 206, emoji: '🌯' },
            'taco': { name: 'Тако', cal: 210, emoji: '🌮' },
            'quesadilla': { name: 'Кесаділья', cal: 227, emoji: '🫔' },
            'nachos': { name: 'Начос', cal: 316, emoji: '🧀' },
            'falafel': { name: 'Фалафель', cal: 333, emoji: '🧆' },
            'hummus': { name: 'Хумус', cal: 166, emoji: '🫘' },
            'kebab': { name: 'Кебаб', cal: 279, emoji: '🥙' },
            'shawarma': { name: 'Шаварма', cal: 230, emoji: '🌯' },
            'dumplings': { name: 'Вареники', cal: 210, emoji: '🥟' },
            'borscht': { name: 'Борщ', cal: 50, emoji: '🍲' },
            'varenyky': { name: 'Вареники', cal: 210, emoji: '🥟' },
            'deruny': { name: 'Деруни', cal: 180, emoji: '🥞' },
            'syrnyky': { name: 'Сирники', cal: 180, emoji: '🥞' },
            'mlyntsi': { name: 'Млинці', cal: 230, emoji: '🥞' },
            
            // Салати
            'caesar_salad': { name: 'Салат Цезар', cal: 127, emoji: '🥗' },
            'greek_salad': { name: 'Грецький салат', cal: 100, emoji: '🥗' },
            'cobb_salad': { name: 'Кобб-салат', cal: 140, emoji: '🥗' },
            'caprese': { name: 'Капрезе', cal: 160, emoji: '🥗' },
            'coleslaw': { name: 'Коуслав', cal: 150, emoji: '🥗' },
            'potato_salad': { name: 'Картопляний салат', cal: 143, emoji: '🥗' },
            'fruit_salad': { name: 'Фруктовий салат', cal: 50, emoji: '🥗' },
            
            // Солодощі
            'chocolate': { name: 'Шоколад', cal: 546, emoji: '🍫' },
            'cake': { name: 'Торт', cal: 352, emoji: '🍰' },
            'pie': { name: 'Пиріг', cal: 237, emoji: '🥧' },
            'brownie': { name: 'Брауні', cal: 466, emoji: '🍫' },
            'cheesecake': { name: 'Чізкейк', cal: 321, emoji: '🍰' },
            'tiramisu': { name: 'Тірамісу', cal: 250, emoji: '🍰' },
            'cupcake': { name: 'Кекс', cal: 305, emoji: '🧁' },
            'macaron': { name: 'Макарон', cal: 350, emoji: '🍪' },
            'baklava': { name: 'Баклава', cal: 527, emoji: '🍯' },
            'cannoli': { name: 'Каннолі', cal: 310, emoji: '🍩' },
            'churro': { name: 'Чуррос', cal: 350, emoji: '🍩' },
            'creme_brulee': { name: 'Крем-брюле', cal: 350, emoji: '🍮' },
            'panna_cotta': { name: 'Панна-котта', cal: 310, emoji: '🍮' },
            'mousse': { name: 'Мус', cal: 180, emoji: '🍮' },
            'pudding': { name: 'Пудинг', cal: 122, emoji: '🍮' },
            
            // Сніданок
            'cereal': { name: 'Гранули', cal: 379, emoji: '🥣' },
            'oatmeal': { name: 'Вівсянка', cal: 68, emoji: '🥣' },
            'porridge': { name: 'Каша', cal: 71, emoji: '🥣' },
            'granola': { name: 'Гранола', cal: 471, emoji: '🥣' },
            'muesli': { name: 'Мюслі', cal: 340, emoji: '🥣' },
            'eggs': { name: 'Яйця', cal: 155, emoji: '🥚' },
            'egg': { name: 'Яйце', cal: 78, emoji: '🥚' },
            'omelette': { name: 'Омлет', cal: 154, emoji: '🍳' },
            'scrambled_eggs': { name: 'Яйця-болтунці', cal: 148, emoji: '🍳' },
            'fried_eggs': { name: 'Смажені яйця', cal: 196, emoji: '🍳' },
            'boiled_eggs': { name: 'Варені яйця', cal: 155, emoji: '🥚' },
            'french_toast': { name: 'Тост з яйцем', cal: 227, emoji: '🍞' },
            
            // Напої
            'coffee': { name: 'Кава', cal: 2, emoji: '☕' },
            'tea': { name: 'Чай', cal: 2, emoji: '🍵' },
            'juice': { name: 'Сік', cal: 45, emoji: '🧃' },
            'soda': { name: 'Газировка', cal: 41, emoji: '🥤' },
            'beer': { name: 'Пиво', cal: 43, emoji: '🍺' },
            'wine': { name: 'Вино', cal: 83, emoji: '🍷' },
            'water': { name: 'Вода', cal: 0, emoji: '💧' },
            'smoothie': { name: 'Смузі', cal: 120, emoji: '🥤' },
            'milkshake': { name: 'Мілкшейк', cal: 230, emoji: '🥤' },
            'hot_chocolate': { name: 'Какао', cal: 75, emoji: '☕' },
            'latte': { name: 'Латте', cal: 135, emoji: '☕' },
            'cappuccino': { name: 'Капучіно', cal: 80, emoji: '☕' },
            'espresso': { name: 'Еспресо', cal: 5, emoji: '☕' },
            'lemonade': { name: 'Лимонад', cal: 40, emoji: '🍋' },
            
            // Горіхи та насіння
            'nuts': { name: 'Горіхи', cal: 607, emoji: '🥜' },
            'almonds': { name: 'Мигдаль', cal: 579, emoji: '🥜' },
            'cashews': { name: 'Кеш\'ю', cal: 553, emoji: '🥜' },
            'peanuts': { name: 'Арахіс', cal: 567, emoji: '🥜' },
            'walnuts': { name: 'Волоські горіхи', cal: 654, emoji: '🥜' },
            'pecans': { name: 'Пекан', cal: 691, emoji: '🥜' },
            'pistachios': { name: 'Фісташки', cal: 560, emoji: '🥜' },
            'hazelnuts': { name: 'Фундук', cal: 628, emoji: '🥜' },
            
            // Соуси
            'ketchup': { name: 'Кетчуп', cal: 112, emoji: '🍅' },
            'mustard': { name: 'Гірчиця', cal: 66, emoji: '🟡' },
            'mayonnaise': { name: 'Майонез', cal: 680, emoji: '🥚' },
            'salsa': { name: 'Сальса', cal: 36, emoji: '🍅' },
            'guacamole': { name: 'Гуакамоле', cal: 151, emoji: '🥑' },
            'pesto': { name: 'Песто', cal: 388, emoji: '🌿' },
            'bbq_sauce': { name: 'Соус BBQ', cal: 172, emoji: '🍶' },
            'soy_sauce': { name: 'Соєвий соус', cal: 53, emoji: '🍶' },
            
            // Бобові
            'lentils': { name: 'Сочевиця', cal: 116, emoji: '🫘' },
            'chickpeas': { name: 'Нут', cal: 164, emoji: '🫘' },
            'tofu': { name: 'Тофу', cal: 76, emoji: '🧊' },
            'tempeh': { name: 'Темпех', cal: 195, emoji: '🧊' },
            'edamame': { name: 'Едамаме', cal: 121, emoji: '🫛' },
            
            // Готові страви (додаткові)
            'french_fries': { name: 'Картопля фрі', cal: 312, emoji: '🍟' },
            'fries': { name: 'Картопля фрі', cal: 312, emoji: '🍟' },
            'chips': { name: 'Чіпси', cal: 536, emoji: '🍟' },
            'onion_rings': { name: 'Кільця цибулі', cal: 411, emoji: '🧅' },
            'mozzarella_sticks': { name: 'Палички моцарели', cal: 360, emoji: '🧀' },
            'spring_rolls': { name: 'Літні роли', cal: 149, emoji: '🥟' },
            'pierogi': { name: 'Пельмені', cal: 200, emoji: '🥟' },
            'ravioli': { name: 'Равіолі', cal: 180, emoji: '🥟' },
            'gnocchi': { name: 'Ньоккі', cal: 133, emoji: '🍝' },
            'tortellini': { name: 'Тортелліні', cal: 160, emoji: '🍝' },
            'penne': { name: 'Пенне', cal: 130, emoji: '🍝' },
            'rigatoni': { name: 'Рігатоні', cal: 130, emoji: '🍝' },
            'linguine': { name: 'Лінгвіне', cal: 130, emoji: '🍝' },
            'farfalle': { name: 'Метелики', cal: 130, emoji: '🍝' },
            'fettuccine': { name: 'Феттучіні', cal: 130, emoji: '🍝' },
            'macaroni': { name: 'Макарони', cal: 131, emoji: '🍝' },
            'spaghetti_bolognese': { name: 'Спагетті Болоньєзе', cal: 150, emoji: '🍝' },
            'spaghetti_carbonara': { name: 'Спагетті Карбонара', cal: 190, emoji: '🍝' },
            'fettuccine_alfredo': { name: 'Феттучіні Альфредо', cal: 220, emoji: '🍝' },
            
            // Піца (додаткові)
            'hawaiian_pizza': { name: 'Гавайська піца', cal: 240, emoji: '🍕' },
            'meat_lovers': { name: 'Піца з м\'ясом', cal: 320, emoji: '🍕' },
            'veggie_pizza': { name: 'Овочева піца', cal: 220, emoji: '🍕' },
            'bbq_chicken_pizza': { name: 'Піца з BBQ куркою', cal: 280, emoji: '🍕' },
            
            // Бургери (додаткові)
            'bacon_cheeseburger': { name: 'Бекон-чізбургер', cal: 390, emoji: '🍔' },
            'double_cheeseburger': { name: 'Двійний чізбургер', cal: 460, emoji: '🍔' },
            'veggie_burger': { name: 'Овочевий бургер', cal: 220, emoji: '🍔' },
            'turkey_burger': { name: 'Бургер з індички', cal: 240, emoji: '🍔' },
            'chicken_burger': { name: 'Курячий бургер', cal: 280, emoji: '🍔' },
            'fish_burger': { name: 'Рибний бургер', cal: 260, emoji: '🍔' },
            
            // Торти (додаткові)
            'chocolate_cake': { name: 'Шоколадний торт', cal: 352, emoji: '🍫' },
            'vanilla_cake': { name: 'Ванільний торт', cal: 340, emoji: '🎂' },
            'red_velvet': { name: 'Червоний оксамит', cal: 370, emoji: '🎂' },
            'carrot_cake': { name: 'Морквяний торт', cal: 340, emoji: '🎂' },
            'black_forest': { name: 'Чорний ліс', cal: 340, emoji: '🎂' },
            'sponge_cake': { name: 'Бісквіт', cal: 320, emoji: '🎂' },
            'pound_cake': { name: 'Паунд-кейк', cal: 380, emoji: '🎂' },
            'fruit_cake': { name: 'Фруктовий торт', cal: 320, emoji: '🎂' },
            
            // Пироги (додаткові)
            'apple_pie': { name: 'Яблучний пиріг', cal: 237, emoji: '🥧' },
            'cherry_pie': { name: 'Вишневий пиріг', cal: 260, emoji: '🥧' },
            'pumpkin_pie': { name: 'Гарбузовий пиріг', cal: 243, emoji: '🥧' },
            'pecan_pie': { name: 'Пекановий пиріг', cal: 430, emoji: '🥧' },
            'blueberry_pie': { name: 'Чорничний пиріг', cal: 245, emoji: '🥧' },
            'key_lime_pie': { name: 'Лаймовий пиріг', cal: 360, emoji: '🥧' },
            'lemon_meringue': { name: 'Лимонний меренг', cal: 310, emoji: '🥧' },
            
            // Морозиво (додаткові)
            'vanilla_ice_cream': { name: 'Ванільне морозиво', cal: 207, emoji: '🍨' },
            'chocolate_ice_cream': { name: 'Шоколадне морозиво', cal: 216, emoji: '🍫' },
            'strawberry_ice_cream': { name: 'Полуничне морозиво', cal: 192, emoji: '🍓' },
            'cookie_dough': { name: 'Морозиво з тістом', cal: 230, emoji: '🍪' },
            'mint_chocolate_chip': { name: 'М\'ятне з шоколадом', cal: 215, emoji: '🍫' },
            'rocky_road': { name: 'Рокі-роуд', cal: 240, emoji: '🍫' },
            'neapolitan': { name: 'Неаполітан', cal: 200, emoji: '🍨' },
            'sorbet': { name: 'Сорбе', cal: 120, emoji: '🍨' },
            'gelato': { name: 'Джелато', cal: 191, emoji: '🍨' },
            'frozen_yogurt': { name: 'Заморожений йогурт', cal: 127, emoji: '🍨' },
            
            // Супи (додаткові)
            'chicken_soup': { name: 'Курячий суп', cal: 56, emoji: '🍲' },
            'tomato_soup': { name: 'Томатний суп', cal: 72, emoji: '🍅' },
            'minestrone': { name: 'Мінестроне', cal: 82, emoji: '🍲' },
            'clam_chowder': { name: 'Молюсковий суп', cal: 101, emoji: '🍲' },
            'mushroom_soup': { name: 'Грибний суп', cal: 60, emoji: '🍄' },
            'onion_soup': { name: 'Цибулевий суп', cal: 48, emoji: '🧅' },
            'broccoli_soup': { name: 'Суп з броколі', cal: 60, emoji: '🥦' },
            'pumpkin_soup': { name: 'Гарбузовий суп', cal: 55, emoji: '🎃' },
            'lentil_soup': { name: 'Сочевичний суп', cal: 130, emoji: '🫘' },
            'vegetable_soup': { name: 'Овочевий суп', cal: 50, emoji: '🥕' },
            'beef_stew': { name: 'Тушкована яловичина', cal: 110, emoji: '🥩' },
            
            // Японська (додаткові)
            'tempura': { name: 'Темпура', cal: 227, emoji: '🍤' },
            'teriyaki': { name: 'Теріякі', cal: 180, emoji: '🍖' },
            'yakitori': { name: 'Якіторі', cal: 170, emoji: '🍢' },
            'tonkatsu': { name: 'Тонкацу', cal: 250, emoji: '🍖' },
            'okonomiyaki': { name: 'Окономіякі', cal: 180, emoji: '🥞' },
            'takoyaki': { name: 'Такоякі', cal: 200, emoji: '🐙' },
            'udon': { name: 'Удон', cal: 140, emoji: '🍜' },
            'soba': { name: 'Соба', cal: 130, emoji: '🍜' },
            'miso_soup': { name: 'Місо-суп', cal: 42, emoji: '🍲' },
            'edamame': { name: 'Едамаме', cal: 121, emoji: '🫛' },
            'onigiri': { name: 'Оніґірі', cal: 180, emoji: '🍙' },
            'bento': { name: 'Бенто', cal: 500, emoji: '🍱' },
            'matcha': { name: 'Матча', cal: 3, emoji: '🍵' },
            'mochi': { name: 'Мочі', cal: 250, emoji: '🍡' },
            
            // Корейська (додаткові)
            'bibimbap': { name: 'Бібімбап', cal: 180, emoji: '🍚' },
            'bulgogi': { name: 'Бульгогі', cal: 200, emoji: '🥩' },
            'galbi': { name: 'Гальбі', cal: 220, emoji: '🥩' },
            'tteokbokki': { name: 'Ттокбоккі', cal: 200, emoji: '🍡' },
            'japchae': { name: 'Япчхе', cal: 160, emoji: '🍜' },
            'kimchi': { name: 'Кімчі', cal: 23, emoji: '🥬' },
            'jjigae': { name: 'Чіге', cal: 80, emoji: '🍲' },
            'samgyeopsal': { name: 'Самгйопсаль', cal: 260, emoji: '🥩' },
            'kimbap': { name: 'Кімбап', cal: 200, emoji: '🍙' },
            'hotteok': { name: 'Хотток', cal: 250, emoji: '🥞' },
            'tteok': { name: 'Тток', cal: 200, emoji: '🍡' },
            
            // Китайська (додаткові)
            'dim_sum': { name: 'Дім-сам', cal: 150, emoji: '🥟' },
            'congee': { name: 'Конджі', cal: 60, emoji: '🥣' },
            'char_siu': { name: 'Ча-сіу', cal: 220, emoji: '🍖' },
            'kung_pao': { name: 'Кунг-пао', cal: 180, emoji: '🍗' },
            'mapo_tofu': { name: 'Мапо тофу', cal: 130, emoji: '🧊' },
            'wonton_soup': { name: 'Суп з вонтоном', cal: 110, emoji: '🥟' },
            'hot_and_sour_soup': { name: 'Гостро-кислий суп', cal: 80, emoji: '🍲' },
            'egg_drop_soup': { name: 'Суп з яйцем', cal: 65, emoji: '🥚' },
            'peking_duck': { name: 'Пекінська качка', cal: 337, emoji: '🦆' },
            'spring_rolls': { name: 'Літні роли', cal: 149, emoji: '🥟' },
            'dumplings': { name: 'Пельмені', cal: 200, emoji: '🥟' },
            'chow_mein': { name: 'Чоу мейн', cal: 180, emoji: '🍜' },
            'lo_mein': { name: 'Ло мейн', cal: 170, emoji: '🍜' },
            'general_tso': { name: 'Дженерал Цо', cal: 200, emoji: '🍗' },
            'orange_chicken': { name: 'Апельсинова курка', cal: 220, emoji: '🍗' },
            'sweet_and_sour': { name: 'Кисло-солодке', cal: 150, emoji: '🍖' },
            'xiao_long_bao': { name: 'Сяо Лун Бао', cal: 200, emoji: '🥟' },
            
            // В'єтнамська (додаткові)
            'pho': { name: 'Фо', cal: 120, emoji: '🍜' },
            'banh_mi': { name: 'Бань-мі', cal: 200, emoji: '🥖' },
            'bun_cha': { name: 'Бун Ча', cal: 180, emoji: '🍜' },
            'goi_cuon': { name: 'Гой Куон', cal: 120, emoji: '🥟' },
            'com_tam': { name: 'Ком Там', cal: 190, emoji: '🍚' },
            'bun_bo_hue': { name: 'Бун Бо Хюе', cal: 150, emoji: '🍜' },
            'banh_xeo': { name: 'Бань Сео', cal: 180, emoji: '🥞' },
            
            // Тайська (додаткові)
            'pad_thai': { name: 'Пад Тай', cal: 190, emoji: '🍜' },
            'green_curry': { name: 'Зелене каррі', cal: 120, emoji: '🍛' },
            'red_curry': { name: 'Червоне каррі', cal: 130, emoji: '🍛' },
            'massaman_curry': { name: 'Массаман', cal: 140, emoji: '🍛' },
            'tom_yum': { name: 'Том Ям', cal: 80, emoji: '🍲' },
            'tom_kha': { name: 'Том Кха', cal: 90, emoji: '🍲' },
            'som_tam': { name: 'Сом Там', cal: 90, emoji: '🥗' },
            'larb': { name: 'Ларб', cal: 150, emoji: '🥗' },
            'pad_see_ew': { name: 'Пад Сі Іу', cal: 170, emoji: '🍜' },
            'pad_kra_pao': { name: 'Пад Кепао', cal: 160, emoji: '🍜' },
            'khao_soi': { name: 'Кхао Сой', cal: 180, emoji: '🍜' },
            'mango_sticky_rice': { name: 'Манго з рисом', cal: 250, emoji: '🥭' },
            
            // Індійська (додаткові)
            'butter_chicken': { name: 'Курка в маслі', cal: 190, emoji: '🍗' },
            'chicken_tikka_masala': { name: 'Тіка Масала', cal: 160, emoji: '🍗' },
            'biryani': { name: 'Бір\'яні', cal: 180, emoji: '🍚' },
            'dal': { name: 'Дал', cal: 120, emoji: '🫘' },
            'samosa': { name: 'Самоса', cal: 260, emoji: '🥟' },
            'naan': { name: 'Наан', cal: 310, emoji: '🫓' },
            'palak_paneer': { name: 'Палак Панір', cal: 140, emoji: '🧀' },
            'chana_masala': { name: 'Чана Масала', cal: 150, emoji: '🫘' },
            'rogan_josh': { name: 'Роган-джош', cal: 170, emoji: '🥩' },
            'vindaloo': { name: 'Віндалу', cal: 160, emoji: '🍛' },
            'korma': { name: 'Корма', cal: 150, emoji: '🍛' },
            'tandoori': { name: 'Тандурі', cal: 180, emoji: '🍗' },
            'pakora': { name: 'Пакора', cal: 250, emoji: '🥟' },
            'chai': { name: 'Чай', cal: 50, emoji: '🍵' },
            'masala_chai': { name: 'Масала Чай', cal: 70, emoji: '🍵' },
            'mango_lassi': { name: 'Манго Лассі', cal: 120, emoji: '🥤' },
            'gulab_jamun': { name: 'Гулаб Джамун', cal: 350, emoji: '🍩' },
            'jalebi': { name: 'Джалебі', cal: 400, emoji: '🍩' },
            'kheer': { name: 'Кхір', cal: 150, emoji: '🍮' },
            'paneer_tikka': { name: 'Панір Тіка', cal: 200, emoji: '🧀' },
            'aloo_gobi': { name: 'Алу Гобі', cal: 120, emoji: '🥔' },
            'saag': { name: 'Сааг', cal: 100, emoji: '🥬' },
            'raita': { name: 'Райта', cal: 60, emoji: '🥛' },
            
            // Середземноморська (додаткові)
            'moussaka': { name: 'Мусака', cal: 130, emoji: '🍆' },
            'spanakopita': { name: 'Спанакопіта', cal: 230, emoji: '🥧' },
            'souvlaki': { name: 'Сувлакі', cal: 220, emoji: '🍢' },
            'gyro': { name: 'Гірос', cal: 215, emoji: '🌯' },
            'tzatziki': { name: 'Цацикі', cal: 100, emoji: '🥛' },
            'dolma': { name: 'Долма', cal: 120, emoji: '🥟' },
            'pastitsio': { name: 'Пастиціо', cal: 150, emoji: '🍝' },
            'gemista': { name: 'Джеміста', cal: 100, emoji: '🍅' },
            'tiropita': { name: 'Тіропіта', cal: 250, emoji: '🥧' },
            'baklava': { name: 'Баклава', cal: 527, emoji: '🍯' },
            'galaktoboureko': { name: 'Галактобуреко', cal: 300, emoji: '🥧' },
            'tabbouleh': { name: 'Таббуле', cal: 100, emoji: '🥗' },
            'fattoush': { name: 'Фаттуш', cal: 90, emoji: '🥗' },
            'baba_ganoush': { name: 'Баба-гануш', cal: 130, emoji: '🍆' },
            'hummus': { name: 'Хумус', cal: 166, emoji: '🫘' },
            'falafel': { name: 'Фалафель', cal: 333, emoji: '🧆' },
            'shawarma': { name: 'Шаварма', cal: 230, emoji: '🌯' },
            'kebab': { name: 'Кебаб', cal: 279, emoji: '🥙' },
            'lahmacun': { name: 'Лахмаджун', cal: 220, emoji: '🍕' },
            'pide': { name: 'Піде', cal: 250, emoji: '🥧' },
            'kunafa': { name: 'Кунафа', cal: 350, emoji: '🍮' },
            
            // Грецька (додаткові)
            'moussaka': { name: 'Мусака', cal: 130, emoji: '🍆' },
            'spanakopita': { name: 'Спанакопіта', cal: 230, emoji: '🥧' },
            'souvlaki': { name: 'Сувлакі', cal: 220, emoji: '🍢' },
            'gyro': { name: 'Гірос', cal: 215, emoji: '🌯' },
            'tzatziki': { name: 'Цацикі', cal: 100, emoji: '🥛' },
            'dolma': { name: 'Долма', cal: 120, emoji: '🥟' },
            'pastitsio': { name: 'Пастиціо', cal: 150, emoji: '🍝' },
            'gemista': { name: 'Джеміста', cal: 100, emoji: '🍅' },
            'tiropita': { name: 'Тіропіта', cal: 250, emoji: '🥧' },
            'galaktoboureko': { name: 'Галактобуреко', cal: 300, emoji: '🥧' },
            'tabbouleh': { name: 'Таббуле', cal: 100, emoji: '🥗' },
            'fattoush': { name: 'Фаттуш', cal: 90, emoji: '🥗' },
            'baba_ganoush': { name: 'Баба-гануш', cal: 130, emoji: '🍆' },
            
            // Іспанська (додаткові)
            'paella': { name: 'Паелья', cal: 172, emoji: '🥘' },
            'tortilla': { name: 'Тортілья', cal: 150, emoji: '🥚' },
            'churros': { name: 'Чуррос', cal: 350, emoji: '🍩' },
            'gazpacho': { name: 'Гаспачо', cal: 40, emoji: '🍅' },
            'croquetas': { name: 'Крокетас', cal: 200, emoji: '🥟' },
            'patatas_bravas': { name: 'Пататас Бравас', cal: 180, emoji: '🥔' },
            'pulpo': { name: 'Пульпо', cal: 120, emoji: '🐙' },
            'jamon': { name: 'Хамон', cal: 250, emoji: '🥩' },
            'pimientos_de_padron': { name: 'Пім\'єнто', cal: 25, emoji: '🫑' },
            'pan_con_tomate': { name: 'Пан кон Томате', cal: 150, emoji: '🍞' },
            
            // Німецька (додаткові)
            'sauerkraut': { name: 'Квашена капуста', cal: 20, emoji: '🥬' },
            'bratwurst': { name: 'Братвурст', cal: 300, emoji: '🌭' },
            'pretzel': { name: 'Брецель', cal: 250, emoji: '🥨' },
            'schnitzel': { name: 'Шніцель', cal: 300, emoji: '🍖' },
            'spätzle': { name: 'Шпецле', cal: 150, emoji: '🍝' },
            'kartoffelpuffer': { name: 'Картопляні оладки', cal: 200, emoji: '🥔' },
            'eintopf': { name: 'Ейнтопф', cal: 80, emoji: '🍲' },
            'rouladen': { name: 'Руладен', cal: 200, emoji: '🥩' },
            'strudel': { name: 'Струдель', cal: 270, emoji: '🥧' },
            'black_forest_cake': { name: 'Чорний ліс', cal: 340, emoji: '🎂' },
            
            // Французька (додаткові)
            'croissant': { name: 'Круассан', cal: 406, emoji: '🥐' },
            'baguette': { name: 'Багет', cal: 270, emoji: '🥖' },
            'crepe': { name: 'Креп', cal: 167, emoji: '🥞' },
            'quiche': { name: 'Кіш', cal: 200, emoji: '🥧' },
            'ratatouille': { name: 'Рататуй', cal: 80, emoji: '🍆' },
            'coq_au_vin': { name: 'Кок-о-Вен', cal: 180, emoji: '🍗' },
            'beef_bourguignon': { name: 'Беф-Бургіньйон', cal: 200, emoji: '🥩' },
            'onion_soup': { name: 'Цибулевий суп', cal: 48, emoji: '🧅' },
            'creme_brulee': { name: 'Крем-брюле', cal: 350, emoji: '🍮' },
            'tarte_tatin': { name: 'Тарт Татен', cal: 280, emoji: '🥧' },
            'macarons': { name: 'Макарони', cal: 350, emoji: '🍪' },
            'eclair': { name: 'Еклер', cal: 320, emoji: '🍩' },
            'profiterole': { name: 'Профітроль', cal: 300, emoji: '🍩' },
            
            // Італійська (додаткові)
            'pizza_margherita': { name: 'Маргарита', cal: 250, emoji: '🍕' },
            'pasta_carbonara': { name: 'Карбонара', cal: 190, emoji: '🍝' },
            'risotto': { name: 'Різотто', cal: 120, emoji: '🍚' },
            'osso_buco': { name: 'Оссо Буко', cal: 200, emoji: '🥩' },
            'bruschetta': { name: 'Брускетта', cal: 160, emoji: '🍞' },
            'caprese': { name: 'Капрезе', cal: 160, emoji: '🥗' },
            'minestrone': { name: 'Мінестроне', cal: 82, emoji: '🍲' },
            'prosciutto': { name: 'Прошутто', cal: 250, emoji: '🥩' },
            'parmigiana': { name: 'Парміджана', cal: 160, emoji: '🍆' },
            
            // Японська (додаткові)
            'tempura': { name: 'Темпура', cal: 227, emoji: '🍤' },
            'teriyaki': { name: 'Теріякі', cal: 180, emoji: '🍖' },
            'yakitori': { name: 'Якіторі', cal: 170, emoji: '🍢' },
            'tonkatsu': { name: 'Тонкацу', cal: 250, emoji: '🍖' },
            'okonomiyaki': { name: 'Окономіякі', cal: 180, emoji: '🥞' },
            'takoyaki': { name: 'Такоякі', cal: 200, emoji: '🐙' },
            'udon': { name: 'Удон', cal: 140, emoji: '🍜' },
            'soba': { name: 'Соба', cal: 130, emoji: '🍜' },
            'miso_soup': { name: 'Місо-суп', cal: 42, emoji: '🍲' },
            'onigiri': { name: 'Оніґірі', cal: 180, emoji: '🍙' },
            'bento': { name: 'Бенто', cal: 500, emoji: '🍱' },
            'matcha': { name: 'Матча', cal: 3, emoji: '🍵' },
            'mochi': { name: 'Мочі', cal: 250, emoji: '🍡' },
            
            // Корейська (додаткові)
            'bibimbap': { name: 'Бібімбап', cal: 180, emoji: '🍚' },
            'bulgogi': { name: 'Бульгогі', cal: 200, emoji: '🥩' },
            'galbi': { name: 'Гальбі', cal: 220, emoji: '🥩' },
            'tteokbokki': { name: 'Ттокбоккі', cal: 200, emoji: '🍡' },
            'japchae': { name: 'Япчхе', cal: 160, emoji: '🍜' },
            'kimchi': { name: 'Кімчі', cal: 23, emoji: '🥬' },
            'jjigae': { name: 'Чіге', cal: 80, emoji: '🍲' },
            'samgyeopsal': { name: 'Самгйопсаль', cal: 260, emoji: '🥩' },
            'kimbap': { name: 'Кімбап', cal: 200, emoji: '🍙' },
            'hotteok': { name: 'Хотток', cal: 250, emoji: '🥞' },
            'tteok': { name: 'Тток', cal: 200, emoji: '🍡' },
            
            // Китайська (додаткові)
            'dim_sum': { name: 'Дім-сам', cal: 150, emoji: '🥟' },
            'congee': { name: 'Конджі', cal: 60, emoji: '🥣' },
            'char_siu': { name: 'Ча-сіу', cal: 220, emoji: '🍖' },
            'kung_pao': { name: 'Кунг-пао', cal: 180, emoji: '🍗' },
            'mapo_tofu': { name: 'Мапо тофу', cal: 130, emoji: '🧊' },
            'wonton_soup': { name: 'Суп з вонтоном', cal: 110, emoji: '🥟' },
            'hot_and_sour_soup': { name: 'Гостро-кислий суп', cal: 80, emoji: '🍲' },
            'egg_drop_soup': { name: 'Суп з яйцем', cal: 65, emoji: '🥚' },
            'peking_duck': { name: 'Пекінська качка', cal: 337, emoji: '🦆' },
            'spring_rolls': { name: 'Літні роли', cal: 149, emoji: '🥟' },
            'dumplings': { name: 'Пельмені', cal: 200, emoji: '🥟' },
            'chow_mein': { name: 'Чоу мейн', cal: 180, emoji: '🍜' },
            'lo_mein': { name: 'Ло мейн', cal: 170, emoji: '🍜' },
            'general_tso': { name: 'Дженерал Цо', cal: 200, emoji: '🍗' },
            'orange_chicken': { name: 'Апельсинова курка', cal: 220, emoji: '🍗' },
            'sweet_and_sour': { name: 'Кисло-солодке', cal: 150, emoji: '🍖' },
            'xiao_long_bao': { name: 'Сяо Лун Бао', cal: 200, emoji: '🥟' },
            
            // В'єтнамська (додаткові)
            'pho': { name: 'Фо', cal: 120, emoji: '🍜' },
            'banh_mi': { name: 'Бань-мі', cal: 200, emoji: '🥖' },
            'bun_cha': { name: 'Бун Ча', cal: 180, emoji: '🍜' },
            'goi_cuon': { name: 'Гой Куон', cal: 120, emoji: '🥟' },
            'com_tam': { name: 'Ком Там', cal: 190, emoji: '🍚' },
            'bun_bo_hue': { name: 'Бун Бо Хюе', cal: 150, emoji: '🍜' },
            'banh_xeo': { name: 'Бань Сео', cal: 180, emoji: '🥞' },
            
            // Тайська (додаткові)
            'pad_thai': { name: 'Пад Тай', cal: 190, emoji: '🍜' },
            'green_curry': { name: 'Зелене каррі', cal: 120, emoji: '🍛' },
            'red_curry': { name: 'Червоне каррі', cal: 130, emoji: '🍛' },
            'massaman_curry': { name: 'Массаман', cal: 140, emoji: '🍛' },
            'tom_yum': { name: 'Том Ям', cal: 80, emoji: '🍲' },
            'tom_kha': { name: 'Том Кха', cal: 90, emoji: '🍲' },
            'som_tam': { name: 'Сом Там', cal: 90, emoji: '🥗' },
            'larb': { name: 'Ларб', cal: 150, emoji: '🥗' },
            'pad_see_ew': { name: 'Пад Сі Іу', cal: 170, emoji: '🍜' },
            'pad_kra_pao': { name: 'Пад Кепао', cal: 160, emoji: '🍜' },
            'khao_soi': { name: 'Кхао Сой', cal: 180, emoji: '🍜' },
            'mango_sticky_rice': { name: 'Манго з рисом', cal: 250, emoji: '🥭' },
            
            // Індійська (додаткові)
            'butter_chicken': { name: 'Курка в маслі', cal: 190, emoji: '🍗' },
            'chicken_tikka_masala': { name: 'Тіка Масала', cal: 160, emoji: '🍗' },
            'biryani': { name: 'Бір\'яні', cal: 180, emoji: '🍚' },
            'dal': { name: 'Дал', cal: 120, emoji: '🫘' },
            'samosa': { name: 'Самоса', cal: 260, emoji: '🥟' },
            'naan': { name: 'Наан', cal: 310, emoji: '🫓' },
            'palak_paneer': { name: 'Палак Панір', cal: 140, emoji: '🧀' },
            'chana_masala': { name: 'Чана Масала', cal: 150, emoji: '🫘' },
            'rogan_josh': { name: 'Роган-джош', cal: 170, emoji: '🥩' },
            'vindaloo': { name: 'Віндалу', cal: 160, emoji: '🍛' },
            'korma': { name: 'Корма', cal: 150, emoji: '🍛' },
            'tandoori': { name: 'Тандурі', cal: 180, emoji: '🍗' },
            'pakora': { name: 'Пакора', cal: 250, emoji: '🥟' },
            'chai': { name: 'Чай', cal: 50, emoji: '🍵' },
            'masala_chai': { name: 'Масала Чай', cal: 70, emoji: '🍵' },
            'mango_lassi': { name: 'Манго Лассі', cal: 120, emoji: '🥤' },
            'gulab_jamun': { name: 'Гулаб Джамун', cal: 350, emoji: '🍩' },
            'jalebi': { name: 'Джалебі', cal: 400, emoji: '🍩' },
            'kheer': { name: 'Кхір', cal: 150, emoji: '🍮' },
            'paneer_tikka': { name: 'Панір Тіка', cal: 200, emoji: '🧀' },
            'aloo_gobi': { name: 'Алу Гобі', cal: 120, emoji: '🥔' },
            'saag': { name: 'Сааг', cal: 100, emoji: '🥬' },
            'raita': { name: 'Райта', cal: 60, emoji: '🥛' },
            
            // Середземноморська (додаткові)
            'moussaka': { name: 'Мусака', cal: 130, emoji: '🍆' },
            'spanakopita': { name: 'Спанакопіта', cal: 230, emoji: '🥧' },
            'souvlaki': { name: 'Сувлакі', cal: 220, emoji: '🍢' },
            'gyro': { name: 'Гірос', cal: 215, emoji: '🌯' },
            'tzatziki': { name: 'Цацикі', cal: 100, emoji: '🥛' },
            'dolma': { name: 'Долма', cal: 120, emoji: '🥟' },
            'pastitsio': { name: 'Пастиціо', cal: 150, emoji: '🍝' },
            'gemista': { name: 'Джеміста', cal: 100, emoji: '🍅' },
            'tiropita': { name: 'Тіропіта', cal: 250, emoji: '🥧' },
            'galaktoboureko': { name: 'Галактобуреко', cal: 300, emoji: '🥧' },
            'tabbouleh': { name: 'Таббуле', cal: 100, emoji: '🥗' },
            'fattoush': { name: 'Фаттуш', cal: 90, emoji: '🥗' },
            'baba_ganoush': { name: 'Баба-гануш', cal: 130, emoji: '🍆' },
            
            // Іспанська (додаткові)
            'paella': { name: 'Паелья', cal: 172, emoji: '🥘' },
            'tortilla': { name: 'Тортілья', cal: 150, emoji: '🥚' },
            'churros': { name: 'Чуррос', cal: 350, emoji: '🍩' },
            'gazpacho': { name: 'Гаспачо', cal: 40, emoji: '🍅' },
            'croquetas': { name: 'Крокетас', cal: 200, emoji: '🥟' },
            'patatas_bravas': { name: 'Пататас Бравас', cal: 180, emoji: '🥔' },
            'pulpo': { name: 'Пульпо', cal: 120, emoji: '🐙' },
            'jamon': { name: 'Хамон', cal: 250, emoji: '🥩' },
            'pimientos_de_padron': { name: 'Пім\'єнто', cal: 25, emoji: '🫑' },
            'pan_con_tomate': { name: 'Пан кон Томате', cal: 150, emoji: '🍞' },
            
            // Німецька (додаткові)
            'sauerkraut': { name: 'Квашена капуста', cal: 20, emoji: '🥬' },
            'bratwurst': { name: 'Братвурст', cal: 300, emoji: '🌭' },
            'pretzel': { name: 'Брецель', cal: 250, emoji: '🥨' },
            'schnitzel': { name: 'Шніцель', cal: 300, emoji: '🍖' },
            'spätzle': { name: 'Шпецле', cal: 150, emoji: '🍝' },
            'kartoffelpuffer': { name: 'Картопляні оладки', cal: 200, emoji: '🥔' },
            'eintopf': { name: 'Ейнтопф', cal: 80, emoji: '🍲' },
            'rouladen': { name: 'Руладен', cal: 200, emoji: '🥩' },
            'strudel': { name: 'Струдель', cal: 270, emoji: '🥧' },
            'black_forest_cake': { name: 'Чорний ліс', cal: 340, emoji: '🎂' },
            
            // Французька (додаткові)
            'croissant': { name: 'Круассан', cal: 406, emoji: '🥐' },
            'baguette': { name: 'Багет', cal: 270, emoji: '🥖' },
            'crepe': { name: 'Креп', cal: 167, emoji: '🥞' },
            'quiche': { name: 'Кіш', cal: 200, emoji: '🥧' },
            'ratatouille': { name: 'Рататуй', cal: 80, emoji: '🍆' },
            'coq_au_vin': { name: 'Кок-о-Вен', cal: 180, emoji: '🍗' },
            'beef_bourguignon': { name: 'Беф-Бургіньйон', cal: 200, emoji: '🥩' },
            'onion_soup': { name: 'Цибулевий суп', cal: 48, emoji: '🧅' },
            'creme_brulee': { name: 'Крем-брюле', cal: 350, emoji: '🍮' },
            'tarte_tatin': { name: 'Тарт Татен', cal: 280, emoji: '🥧' },
            'macarons': { name: 'Макарони', cal: 350, emoji: '🍪' },
            'eclair': { name: 'Еклер', cal: 320, emoji: '🍩' },
            'profiterole': { name: 'Профітроль', cal: 300, emoji: '🍩' },
            
            // Італійська (додаткові)
            'pizza_margherita': { name: 'Маргарита', cal: 250, emoji: '🍕' },
            'pasta_carbonara': { name: 'Карбонара', cal: 190, emoji: '🍝' },
            'risotto': { name: 'Різотто', cal: 120, emoji: '🍚' },
            'osso_buco': { name: 'Оссо Буко', cal: 200, emoji: '🥩' },
            'bruschetta': { name: 'Брускетта', cal: 160, emoji: '🍞' },
            'caprese': { name: 'Капрезе', cal: 160, emoji: '🥗' },
            'minestrone': { name: 'Мінестроне', cal: 82, emoji: '🍲' },
            'prosciutto': { name: 'Прошутто', cal: 250, emoji: '🥩' },
            'parmigiana': { name: 'Парміджана', cal: 160, emoji: '🍆' },
            
            // Японська (додаткові)
            'tempura': { name: 'Темпура', cal: 227, emoji: '🍤' },
            'teriyaki': { name: 'Теріякі', cal: 180, emoji: '🍖' },
            'yakitori': { name: 'Якіторі', cal: 170, emoji: '🍢' },
            'tonkatsu': { name: 'Тонкацу', cal: 250, emoji: '🍖' },
            'okonomiyaki': { name: 'Окономіякі', cal: 180, emoji: '🥞' },
            'takoyaki': { name: 'Такоякі', cal: 200, emoji: '🐙' },
            'udon': { name: 'Удон', cal: 140, emoji: '🍜' },
            'soba': { name: 'Соба', cal: 130, emoji: '🍜' },
            'miso_soup': { name: 'Місо-суп', cal: 42, emoji: '🍲' },
            'onigiri': { name: 'Оніґірі', cal: 180, emoji: '🍙' },
            'bento': { name: 'Бенто', cal: 500, emoji: '🍱' },
            'matcha': { name: 'Матча', cal: 3, emoji: '🍵' },
            'mochi': { name: 'Мочі', cal: 250, emoji: '🍡' },
            
            // Корейська (додаткові)
            'bibimbap': { name: 'Бібімбап', cal: 180, emoji: '🍚' },
            'bulgogi': { name: 'Бульгогі', cal: 200, emoji: '🥩' },
            'galbi': { name: 'Гальбі', cal: 220, emoji: '🥩' },
            'tteokbokki': { name: 'Ттокбоккі', cal: 200, emoji: '🍡' },
            'japchae': { name: 'Япчхе', cal: 160, emoji: '🍜' },
            'kimchi': { name: 'Кімчі', cal: 23, emoji: '🥬' },
            'jjigae': { name: 'Чіге', cal: 80, emoji: '🍲' },
            'samgyeopsal': { name: 'Самгйопсаль', cal: 260, emoji: '🥩' },
            'kimbap': { name: 'Кімбап', cal: 200, emoji: '🍙' },
            'hotteok': { name: 'Хотток', cal: 250, emoji: '🥞' },
            'tteok': { name: 'Тток', cal: 200, emoji: '🍡' },
            
            // Китайська (додаткові)
            'dim_sum': { name: 'Дім-сам', cal: 150, emoji: '🥟' },
            'congee': { name: 'Конджі', cal: 60, emoji: '🥣' },
            'char_siu': { name: 'Ча-сіу', cal: 220, emoji: '🍖' },
            'kung_pao': { name: 'Кунг-пао', cal: 180, emoji: '🍗' },
            'mapo_tofu': { name: 'Мапо тофу', cal: 130, emoji: '🧊' },
            'wonton_soup': { name: 'Суп з вонтоном', cal: 110, emoji: '🥟' },
            'hot_and_sour_soup': { name: 'Гостро-кислий суп', cal: 80, emoji: '🍲' },
            'egg_drop_soup': { name: 'Суп з яйцем', cal: 65, emoji: '🥚' },
            'peking_duck': { name: 'Пекінська качка', cal: 337, emoji: '🦆' },
            'spring_rolls': { name: 'Літні роли', cal: 149, emoji: '🥟' },
            'dumplings': { name: 'Пельмені', cal: 200, emoji: '🥟' },
            'chow_mein': { name: 'Чоу мейн', cal: 180, emoji: '🍜' },
            'lo_mein': { name: 'Ло мейн', cal: 170, emoji: '🍜' },
            'general_tso': { name: 'Дженерал Цо', cal: 200, emoji: '🍗' },
            'orange_chicken': { name: 'Апельсинова курка', cal: 220, emoji: '🍗' },
            'sweet_and_sour': { name: 'Кисло-солодке', cal: 150, emoji: '🍖' },
            'xiao_long_bao': { name: 'Сяо Лун Бао', cal: 200, emoji: '🥟' },
            
            // В'єтнамська (додаткові)
            'pho': { name: 'Фо', cal: 120, emoji: '🍜' },
            'banh_mi': { name: 'Бань-мі', cal: 200, emoji: '🥖' },
            'bun_cha': { name: 'Бун Ча', cal: 180, emoji: '🍜' },
            'goi_cuon': { name: 'Гой Куон', cal: 120, emoji: '🥟' },
            'com_tam': { name: 'Ком Там', cal: 190, emoji: '🍚' },
            'bun_bo_hue': { name: 'Бун Бо Хюе', cal: 150, emoji: '🍜' },
            'banh_xeo': { name: 'Бань Сео', cal: 180, emoji: '🥞' },
            
            // Тайська (додаткові)
            'pad_thai': { name: 'Пад Тай', cal: 190, emoji: '🍜' },
            'green_curry': { name: 'Зелене каррі', cal: 120, emoji: '🍛' },
            'red_curry': { name: 'Червоне каррі', cal: 130, emoji: '🍛' },
            'massaman_curry': { name: 'Массаман', cal: 140, emoji: '🍛' },
            'tom_yum': { name: 'Том Ям', cal: 80, emoji: '🍲' },
            'tom_kha': { name: 'Том Кха', cal: 90, emoji: '🍲' },
            'som_tam': { name: 'Сом Там', cal: 90, emoji: '🥗' },
            'larb': { name: 'Ларб', cal: 150, emoji: '🥗' },
            'pad_see_ew': { name: 'Пад Сі Іу', cal: 170, emoji: '🍜' },
            'pad_kra_pao': { name: 'Пад Кепао', cal: 160, emoji: '🍜' },
            'khao_soi': { name: 'Кхао Сой', cal: 180, emoji: '🍜' },
            'mango_sticky_rice': { name: 'Манго з рисом', cal: 250, emoji: '🥭' },
            
            // Індійська (додаткові)
            'butter_chicken': { name: 'Курка в маслі', cal: 190, emoji: '🍗' },
            'chicken_tikka_masala': { name: 'Тіка Масала', cal: 160, emoji: '🍗' },
            'biryani': { name: 'Бір\'яні', cal: 180, emoji: '🍚' },
            'dal': { name: 'Дал', cal: 120, emoji: '🫘' },
            'samosa': { name: 'Самоса', cal: 260, emoji: '🥟' },
            'naan': { name: 'Наан', cal: 310, emoji: '🫓' },
            'palak_paneer': { name: 'Палак Панір', cal: 140, emoji: '🧀' },
            'chana_masala': { name: 'Чана Масала', cal: 150, emoji: '🫘' },
            'rogan_josh': { name: 'Роган-джош', cal: 170, emoji: '🥩' },
            'vindaloo': { name: 'Віндалу', cal: 160, emoji: '🍛' },
            'korma': { name: 'Корма', cal: 150, emoji: '🍛' },
            'tandoori': { name: 'Тандурі', cal: 180, emoji: '🍗' },
            'pakora': { name: 'Пакора', cal: 250, emoji: '🥟' },
            'chai': { name: 'Чай', cal: 50, emoji: '🍵' },
            'masala_chai': { name: 'Масала Чай', cal: 70, emoji: '🍵' },
            'mango_lassi': { name: 'Манго Лассі', cal: 120, emoji: '🥤' },
            'gulab_jamun': { name: 'Гулаб Джамун', cal: 350, emoji: '🍩' },
            'jalebi': { name: 'Джалебі', cal: 400, emoji: '🍩' },
            'kheer': { name: 'Кхір', cal: 150, emoji: '🍮' },
            'paneer_tikka': { name: 'Панір Тіка', cal: 200, emoji: '🧀' },
            'aloo_gobi': { name: 'Алу Гобі', cal: 120, emoji: '🥔' },
            'saag': { name: 'Сааг', cal: 100, emoji: '🥬' },
            'raita': { name: 'Райта', cal: 60, emoji: '🥛' },
            
            // Середземноморська (додаткові)
            'moussaka': { name: 'Мусака', cal: 130, emoji: '🍆' },
            'spanakopita': { name: 'Спанакопіта', cal: 230, emoji: '🥧' },
            'souvlaki': { name: 'Сувлакі', cal: 220, emoji: '🍢' },
            'gyro': { name: 'Гірос', cal: 215, emoji: '🌯' },
            'tzatziki': { name: 'Цацикі', cal: 100, emoji: '🥛' },
            'dolma': { name: 'Долма', cal: 120, emoji: '🥟' },
            'pastitsio': { name: 'Пастиціо', cal: 150, emoji: '🍝' },
            'gemista': { name: 'Джеміста', cal: 100, emoji: '🍅' },
            'tiropita': { name: 'Тіропіта', cal: 250, emoji: '🥧' },
            'galaktoboureko': { name: 'Галактобуреко', cal: 300, emoji: '🥧' },
            'tabbouleh': { name: 'Таббуле', cal: 100, emoji: '🥗' },
            'fattoush': { name: 'Фаттуш', cal: 90, emoji: '🥗' },
            'baba_ganoush': { name: 'Баба-гануш', cal: 130, emoji: '🍆' },
            
            // Іспанська (додаткові)
            'paella': { name: 'Паелья', cal: 172, emoji: '🥘' },
            'tortilla': { name: 'Тортілья', cal: 150, emoji: '🥚' },
            'churros': { name: 'Чуррос', cal: 350, emoji: '🍩' },
            'gazpacho': { name: 'Гаспачо', cal: 40, emoji: '🍅' },
            'croquetas': { name: 'Крокетас', cal: 200, emoji: '🥟' },
            'patatas_bravas': { name: 'Пататас Бравас', cal: 180, emoji: '🥔' },
            'pulpo': { name: 'Пульпо', cal: 120, emoji: '🐙' },
            'jamon': { name: 'Хамон', cal: 250, emoji: '🥩' },
            'pimientos_de_padron': { name: 'Пім\'єнто', cal: 25, emoji: '🫑' },
            'pan_con_tomate': { name: 'Пан кон Томате', cal: 150, emoji: '🍞' },
            
            // Німецька (додаткові)
            'sauerkraut': { name: 'Квашена капуста', cal: 20, emoji: '🥬' },
            'bratwurst': { name: 'Братвурст', cal: 300, emoji: '🌭' },
            'pretzel': { name: 'Брецель', cal: 250, emoji: '🥨' },
            'schnitzel': { name: 'Шніцель', cal: 300, emoji: '🍖' },
            'spätzle': { name: 'Шпецле', cal: 150, emoji: '🍝' },
            'kartoffelpuffer': { name: 'Картопляні оладки', cal: 200, emoji: '🥔' },
            'eintopf': { name: 'Ейнтопф', cal: 80, emoji: '🍲' },
            'rouladen': { name: 'Руладен', cal: 200, emoji: '🥩' },
            'strudel': { name: 'Струдель', cal: 270, emoji: '🥧' },
            'black_forest_cake': { name: 'Чорний ліс', cal: 340, emoji: '🎂' },
            
            // Французька (додаткові)
            'croissant': { name: 'Круассан', cal: 406, emoji: '🥐' },
            'baguette': { name: 'Багет', cal: 270, emoji: '🥖' },
            'crepe': { name: 'Креп', cal: 167, emoji: '🥞' },
            'quiche': { name: 'Кіш', cal: 200, emoji: '🥧' },
            'ratatouille': { name: 'Рататуй', cal: 80, emoji: '🍆' },
            'coq_au_vin': { name: 'Кок-о-Вен', cal: 180, emoji: '🍗' },
            'beef_bourguignon': { name: 'Беф-Бургіньйон', cal: 200, emoji: '🥩' },
            'onion_soup': { name: 'Цибулевий суп', cal: 48, emoji: '🧅' },
            'creme_brulee': { name: 'Крем-брюле', cal: 350, emoji: '🍮' },
            'tarte_tatin': { name: 'Тарт Татен', cal: 280, emoji: '🥧' },
            'macarons': { name: 'Макарони', cal: 350, emoji: '🍪' },
            'eclair': { name: 'Еклер', cal: 320, emoji: '🍩' },
            'profiterole': { name: 'Профітроль', cal: 300, emoji: '🍩' },
            
            // Італійська (додаткові)
            'pizza_margherita': { name: 'Маргарита', cal: 250, emoji: '🍕' },
            'pasta_carbonara': { name: 'Карбонара', cal: 190, emoji: '🍝' },
            'risotto': { name: 'Різотто', cal: 120, emoji: '🍚' },
            'osso_buco': { name: 'Оссо Буко', cal: 200, emoji: '🥩' },
            'bruschetta': { name: 'Брускетта', cal: 160, emoji: '🍞' },
            'caprese': { name: 'Капрезе', cal: 160, emoji: '🥗' },
            'minestrone': { name: 'Мінестроне', cal: 82, emoji: '🍲' },
            'prosciutto': { name: 'Прошутто', cal: 250, emoji: '🥩' },
            'parmigiana': { name: 'Парміджана', cal: 160, emoji: '🍆' },
            
            // Японська (додаткові)
            'tempura': { name: 'Темпура', cal: 227, emoji: '🍤' },
            'teriyaki': { name: 'Теріякі', cal: 180, emoji: '🍖' },
            'yakitori': { name: 'Якіторі', cal: 170, emoji: '🍢' },
            'tonkatsu': { name: 'Тонкацу', cal: 250, emoji: '🍖' },
            'okonomiyaki': { name: 'Окономіякі', cal: 180, emoji: '🥞' },
            'takoyaki': { name: 'Такоякі', cal: 200, emoji: '🐙' },
            'udon': { name: 'Удон', cal: 140, emoji: '🍜' },
            'soba': { name: 'Соба', cal: 130, emoji: '🍜' },
            'miso_soup': { name: 'Місо-суп', cal: 42, emoji: '🍲' },
            'onigiri': { name: 'Оніґірі', cal: 180, emoji: '🍙' },
            'bento': { name: 'Бенто', cal: 500, emoji: '🍱' },
            'matcha': { name: 'Матча', cal: 3, emoji: '🍵' },
            'mochi': { name: 'Мочі', cal: 250, emoji: '🍡' },
            
            // Корейська (додаткові)
            'bibimbap': { name: 'Бібімбап', cal: 180, emoji: '🍚' },
            'bulgogi': { name: 'Бульгогі', cal: 200, emoji: '🥩' },
            'galbi': { name: 'Гальбі', cal: 220, emoji: '🥩' },
            'tteokbokki': { name: 'Ттокбоккі', cal: 200, emoji: '🍡' },
            'japchae': { name: 'Япчхе', cal: 160, emoji: '🍜' },
            'kimchi': { name: 'Кімчі', cal: 23, emoji: '🥬' },
            'jjigae': { name: 'Чіге', cal: 80, emoji: '🍲' },
            'samgyeopsal': { name: 'Самгйопсаль', cal: 260, emoji: '🥩' },
            'kimbap': { name: 'Кімбап', cal: 200, emoji: '🍙' },
            'hotteok': { name: 'Хотток', cal: 250, emoji: '🥞' },
            'tteok': { name: 'Тток', cal: 200, emoji: '🍡' },
            
            // Китайська (додаткові)
            'dim_sum': { name: 'Дім-сам', cal: 150, emoji: '🥟' },
            'congee': { name: 'Конджі', cal: 60, emoji: '🥣' },
            'char_siu': { name: 'Ча-сіу', cal: 220, emoji: '🍖' },
            'kung_pao': { name: 'Кунг-пао', cal: 180, emoji: '🍗' },
            'mapo_tofu': { name: 'Мапо тофу', cal: 130, emoji: '🧊' },
            'wonton_soup': { name: 'Суп з вонтоном', cal: 110, emoji: '🥟' },
            'hot_and_sour_soup': { name: 'Гостро-кислий суп', cal: 80, emoji: '🍲' },
            'egg_drop_soup': { name: 'Суп з яйцем', cal: 65, emoji: '🥚' },
            'peking_duck': { name: 'Пекінська качка', cal: 337, emoji: '🦆' },
            'spring_rolls': { name: 'Літні роли', cal: 149, emoji: '🥟' },
            'dumplings': { name: 'Пельмені', cal: 200, emoji: '🥟' },
            'chow_mein': { name: 'Чоу мейн', cal: 180, emoji: '🍜' },
            'lo_mein': { name: 'Ло мейн', cal: 170, emoji: '🍜' },
            'general_tso': { name: 'Дженерал Цо', cal: 200, emoji: '🍗' },
            'orange_chicken': { name: 'Апельсинова курка', cal: 220, emoji: '🍗' },
            'sweet_and_sour': { name: 'Кисло-солодке', cal: 150, emoji: '🍖' },
            'xiao_long_bao': { name: 'Сяо Лун Бао', cal: 200, emoji: '🥟' },
            
            // В'єтнамська (додаткові)
            'pho': { name: 'Фо', cal: 120, emoji: '🍜' },
            'banh_mi': { name: 'Бань-мі', cal: 200, emoji: '🥖' },
            'bun_cha': { name: 'Бун Ча', cal: 180, emoji: '🍜' },
            'goi_cuon': { name: 'Гой Куон', cal: 120, emoji: '🥟' },
            'com_tam': { name: 'Ком Там', cal: 190, emoji: '🍚' },
            'bun_bo_hue': { name: 'Бун Бо Хюе', cal: 150, emoji: '🍜' },
            'banh_xeo': { name: 'Бань Сео', cal: 180, emoji: '🥞' },
            
            // Тайська (додаткові)
            'pad_thai': { name: 'Пад Тай', cal: 190, emoji: '🍜' },
            'green_curry': { name: 'Зелене каррі', cal: 120, emoji: '🍛' },
            'red_curry': { name: 'Червоне каррі', cal: 130, emoji: '🍛' },
            'massaman_curry': { name: 'Массаман', cal: 140, emoji: '🍛' },
            'tom_yum': { name: 'Том Ям', cal: 80, emoji: '🍲' },
            'tom_kha': { name: 'Том Кха', cal: 90, emoji: '🍲' },
            'som_tam': { name: 'Сом Там', cal: 90, emoji: '🥗' },
            'larb': { name: 'Ларб', cal: 150, emoji: '🥗' },
            'pad_see_ew': { name: 'Пад Сі Іу', cal: 170, emoji: '🍜' },
            'pad_kra_pao': { name: 'Пад Кепао', cal: 160, emoji: '🍜' },
            'khao_soi': { name: 'Кхао Сой', cal: 180, emoji: '🍜' },
            'mango_sticky_rice': { name: 'Манго з рисом', cal: 250, emoji: '🥭' },
            
            // Індійська (додаткові)
            'butter_chicken': { name: 'Курка в маслі', cal: 190, emoji: '🍗' },
            'chicken_tikka_masala': { name: 'Тіка Масала', cal: 160, emoji: '🍗' },
            'biryani': { name: 'Бір\'яні', cal: 180, emoji: '🍚' },
            'dal': { name: 'Дал', cal: 120, emoji: '🫘' },
            'samosa': { name: 'Самоса', cal: 260, emoji: '🥟' },
            'naan': { name: 'Наан', cal: 310, emoji: '🫓' },
            'palak_paneer': { name: 'Палак Панір', cal: 140, emoji: '🧀' },
            'chana_masala': { name: 'Чана Масала', cal: 150, emoji: '🫘' },
            'rogan_josh': { name: 'Роган-джош', cal: 170, emoji: '🥩' },
            'vindaloo': { name: 'Віндалу', cal: 160, emoji: '🍛' },
            'korma': { name: 'Корма', cal: 150, emoji: '🍛' },
            'tandoori': { name: 'Тандурі', cal: 180, emoji: '🍗' },
            'pakora': { name: 'Пакора', cal: 250, emoji: '🥟' },
            'chai': { name: 'Чай', cal: 50, emoji: '🍵' },
            'masala_chai': { name: 'Масала Чай', cal: 70, emoji: '🍵' },
            'mango_lassi': { name: 'Манго Лассі', cal: 120, emoji: '🥤' },
            'gulab_jamun': { name: 'Гулаб Джамун', cal: 350, emoji: '🍩' },
            'jalebi': { name: 'Джалебі', cal: 400, emoji: '🍩' },
            'kheer': { name: 'Кхір', cal: 150, emoji: '🍮' },
            'paneer_tikka': { name: 'Панір Тіка', cal: 200, emoji: '🧀' },
            'aloo_gobi': { name: 'Алу Гобі', cal: 120, emoji: '🥔' },
            'saag': { name: 'Сааг', cal: 100, emoji: '🥬' },
            'raita': { name: 'Райта', cal: 60, emoji: '🥛' },
            
            // Середземноморська (додаткові)
            'moussaka': { name: 'Мусака', cal: 130, emoji: '🍆' },
            'spanakopita': { name: 'Спанакопіта', cal: 230, emoji: '🥧' },
            'souvlaki': { name: 'Сувлакі', cal: 220, emoji: '🍢' },
            'gyro': { name: 'Гірос', cal: 215, emoji: '🌯' },
            'tzatziki': { name: 'Цацикі', cal: 100, emoji: '🥛' },
            'dolma': { name: 'Долма', cal: 120, emoji: '🥟' },
            'pastitsio': { name: 'Пастиціо', cal: 150, emoji: '🍝' },
            'gemista': { name: 'Джеміста', cal: 100, emoji: '🍅' },
            'tiropita': { name: 'Тіропіта', cal: 250, emoji: '🥧' },
            'galaktoboureko': { name: 'Галактобуреко', cal: 300, emoji: '🥧' },
            'tabbouleh': { name: 'Таббуле', cal: 100, emoji: '🥗' },
            'fattoush': { name: 'Фаттуш', cal: 90, emoji: '🥗' },
            'baba_ganoush': { name: 'Баба-гануш', cal: 130, emoji: '🍆' },
            
            // Іспанська (додаткові)
            'paella': { name: 'Паелья', cal: 172, emoji: '🥘' },
            'tortilla': { name: 'Тортілья', cal: 150, emoji: '🥚' },
            'churros': { name: 'Чуррос', cal: 350, emoji: '🍩' },
            'gazpacho': { name: 'Гаспачо', cal: 40, emoji: '🍅' },
            'croquetas': { name: 'Крокетас', cal: 200, emoji: '🥟' },
            'patatas_bravas': { name: 'Пататас Бравас', cal: 180, emoji: '🥔' },
            'pulpo': { name: 'Пульпо', cal: 120, emoji: '🐙' },
            'jamon': { name: 'Хамон', cal: 250, emoji: '🥩' },
            'pimientos_de_padron': { name: 'Пім\'єнто', cal: 25, emoji: '🫑' },
            'pan_con_tomate': { name: 'Пан кон Томате', cal: 150, emoji: '🍞' },
            
            // Німецька (додаткові)
            'sauerkraut': { name: 'Квашена капуста', cal: 20, emoji: '🥬' },
            'bratwurst': { name: 'Братвурст', cal: 300, emoji: '🌭' },
            'pretzel': { name: 'Брецель', cal: 250, emoji: '🥨' },
            'schnitzel': { name: 'Шніцель', cal: 300, emoji: '🍖' },
            'spätzle': { name: 'Шпецле', cal: 150, emoji: '🍝' },
            'kartoffelpuffer': { name: 'Картопляні оладки', cal: 200, emoji: '🥔' },
            'eintopf': { name: 'Ейнтопф', cal: 80, emoji: '🍲' },
            'rouladen': { name: 'Руладен', cal: 200, emoji: '🥩' },
            'strudel': { name: 'Струдель', cal: 270, emoji: '🥧' },
            'black_forest_cake': { name: 'Чорний ліс', cal: 340, emoji: '🎂' },
            
            // Французька (додаткові)
            'croissant': { name: 'Круассан', cal: 406, emoji: '🥐' },
            'baguette': { name: 'Багет', cal: 270, emoji: '🥖' },
            'crepe': { name: 'Креп', cal: 167, emoji: '🥞' },
            'quiche': { name: 'Кіш', cal: 200, emoji: '🥧' },
            'ratatouille': { name: 'Рататуй', cal: 80, emoji: '🍆' },
            'coq_au_vin': { name: 'Кок-о-Вен', cal: 180, emoji: '🍗' },
            'beef_bourguignon': { name: 'Беф-Бургіньйон', cal: 200, emoji: '🥩' },
            'onion_soup': { name: 'Цибулевий суп', cal: 48, emoji: '🧅' },
            'creme_brulee': { name: 'Крем-брюле', cal: 350, emoji: '🍮' },
            'tarte_tatin': { name: 'Тарт Татен', cal: 280, emoji: '🥧' },
            'macarons': { name: 'Макарони', cal: 350, emoji: '🍪' },
            'eclair': { name: 'Еклер', cal: 320, emoji: '🍩' },
            'profiterole': { name: 'Профітроль', cal: 300, emoji: '🍩' }
        };
        
        // Обробка результату від nateraw/food
        if (data && Array.isArray(data) && data.length > 0) {
            const topResults = data.slice(0, 3).map(item => {
                const itemLabel = item.label ? item.label.toLowerCase().replace(/ /g, '_') : '';
                const foodInfo = calorieDB[itemLabel] || { name: item.label || 'Їжа', cal: 200, emoji: '🍽️' };
                return {
                    name: foodInfo.name,
                    confidence: Math.round((item.score || 0.5) * 100),
                    calories: foodInfo.cal,
                    emoji: foodInfo.emoji
                };
            });
            
            return res.status(200).json({
                success: true,
                dishes: topResults,
                totalCalories: topResults[0].calories
            });
        }
        
        return res.status(200).json({
            success: false,
            error: 'Не вдалося розпізнати'
        });
        
    } catch (error) {
        return res.status(500).json({ error: error.message });
    }
};
